### ISSUE TITLE
Show-InstallationWelcome[Feature] 

### ISSUE THREAD

**Issue by hockink** [PSAppDeployToolkit/PSAppDeployToolkit#1001] opened 2024-05-31 12:43 UTC
### Summary of the new feature / enhancement

When making use of the Show-InstallationWelcome it always says "The following application is about to be installed", this is the text even when using this option in the "Uninstall" portion of PSADT.  This has caused confusion to our clients when we have to force remove the software as they think the software is being installed, but then further down on the screen since we use a countdown it says "the uninstallation will automatically continue in:"

I was wondering if the Show-InstallationWelcome could be updated so that when it's used in the other areas of PSADT the text displayed reflects the section it's being run in.

For instance
Running in the installation area "The following application is about to be installed"
Running in the uninstallation area "The following application is about to be uninstalled"
Running in the repair area "The following application is about to be repaired"

**Comment by Pollewops** [comment] 2024-06-18 11:11
I configured it manually now for 4 languages in the function.
But, yes, this should be default configured that way.

**Comment by mjr4077au** [comment] 2024-10-14 12:29
Duplicate of #41.

**Closed by mjr4077au** 2024-10-14 12:29 UTC
Labels: Type: Idea / Enhancement, Status: Needs Triage
