### ISSUE TITLE
Installation Process dialog is not closing and installation does not finish

### ISSUE THREAD

**Issue by willytheweel** [PSAppDeployToolkit/PSAppDeployToolkit#532] opened 2020-07-14 10:06 UTC
Hello

I have a problem that the installation does not finish after the MSI installation has passed successfully.
The problem only occurs when I use closeapps and the this process is started, e.g. Show-InstallationWelcome -CloseApps '7zFM' -CheckDiskSpace

At the end, the window with the message remains:

[07-14-2020 10:51:37.043] [Post-Installation] [Close-InstallationProgress] :: Function End
[07-14-2020 10:51:37.063] [Post-Installation] [Exit Script] :: 7-zip_17.00 Installation completed with exit code [0].
[07-14-2020 10:51:37.084] [Post-Installation] [Exit Script] :: -------------------------------------------------------------------------------

and the installation is not finish, so i have to kill the powershell.exe manually

It only occurs if the MSI has not yet been installed and the process is started. 
The problem reads similarly to the issue #448 , but I couldn't solve my problem with this solution.
The problem can be reproducible at any time on different machines.
It occurs with the Appdeploytoolkit version 3.7.0, as well as the current 3.8.0. We use Windows 10 1903. The problem does NOT occur on Windows 10 1709.

I also think it has something to do with the $script:ProgressSyncHash.Window.Dispatcher.Thread.ThreadState, because it displays different values when the closeapp process is started or not, or whether the MSI has already been installed or uninstalled. That's $script:ProgressSyncHash.Window.Dispatcher.Thread.ThreadState = WaitSleepJoin

Udo
![Screenshot](https://user-images.githubusercontent.com/68270860/87413277-65c9a180-c5ca-11ea-87c8-9487e4ad04bf.jpg)

**Comment by luki1412** [comment] 2020-07-17 05:49
Did you install 7zip silently?

**Comment by willytheweel** [comment] 2020-07-17 08:34
yes the installation is performed noninteractive. 

The window to close the application also appears and then the MSI is installing. Only in this cases that issue apears.
The "Show-InstallationProgress" dialog then hangs and the Windows logo no longer rotates. See picture.

I have just found a solution to the problem.
The "Update Desktop" function is the problem. If I comment on it then the installation runs through to the end and the "Show-InstallationProgress" closes after that the progress window.
I comment on the update desktop in the "Execute-MSI" function with #Update-desktop and use it instead in the "Exit Script" function after Close-InstallationProgress as here: 

If ($formCloseApps) $formCloseApps.Close

Close the Installation Progress Dialog if running
Close-InstallationProgress
Update-desktop

Udo

![Screenshot2](https://user-images.githubusercontent.com/68270860/87765870-a3236e80-c818-11ea-98c0-25bcd1dc9b73.jpg)

**Comment by luki1412** [comment] 2020-07-17 13:23
Seems strange, that that would be the cause. Can you give me more info as to what your script does so I can replicate this?

**Comment by LitGuy-Ops** [comment] 2020-11-15 20:05
I've also experienced this issue.  For testing purposes I used the below

![image](https://user-images.githubusercontent.com/74510034/99195372-dafcdd00-274a-11eb-8302-1f9e61d74003.png)

Below are the steps that I've performed to reproduce the issue.

1. Using PSExec open an interactive command prompt as the System account
2. Open Notepad so that we will see the prompt to close it
3. When the prompt to close Notepad is displayed, click continue
4. When the prompt to close Notepad is displayed the 2nd time, manually close notepad and click continue to the prompt

After 7-Zip is successfully installed the installation progress window does not close because it's in a WaitSleepJoin state instead of a running state.

**Comment by luki1412** [comment] 2020-11-16 11:27
The problem here is that to replicate this issue you need a machine slow enough so when it starts opening the progress dialog, it takes it so much time that closing it, is started too soon so it isnt in Running state yet. Using your steps did not help me. It closed without issues. I will try to replicate it in another way. I wrote a code that should fix it but I can really test it since I cant replicate the problem :/

**Comment by luki1412** [comment] 2020-11-23 10:35
I modified the function. Can you please download the main script from our repository and test again?

**Closed** 2021-01-08 07:09 UTC
Labels: bug, resolved/implemented

**Comment by getvpro** [comment] 2022-01-07 15:52
oddly, I'm seeing this in 2022
To get around it, I added the following line to the end of my scrcipt:

`Get-process | Where {$_.MainWindowTitle -like "PS App Deploy Toolkit*"} | Where {$_.Name -eq "Powershell"} | Stop-Process -force`

**Comment by niceguy0815** [comment] 2022-01-24 12:25
We have the same Problem here in 2022
Aslo running the PSADT as a scheduled task via IVANTI EPM21 in the SYSTEM CONTEXT on fresh install Win 10 x64 21H2.
The installation is complet but hangs and dose not close. 
![grafik](https://user-images.githubusercontent.com/43955022/150782417-16a681ba-64ad-481f-8f00-37df0caf1b28.png)
The loading animation is spinning but nothing happens.

**Comment by azra1l** [comment] 2024-03-25 23:50
Hi there,

This problem keeps bugging me right now. it started when i tried version 3.9.3 for the first time, we've used 3.8.4 before for a long time without any problems.

I noticed that Show-InstallationProgress would sometimes spawn additional dialogs, instead of updating the first one.
It also appears that the script sometimes has trouble closing the dialog(s), even though script execution has finished.

I use Show-InstallationProgress quite often in complexer packages, to show what's going on.

I thought it was a bug with 3.9.3 and shrugged it off since our existing template worked just fine.

And now it just started happening with 3.8.4 too. 

I just removed all additional Show-InstallationProgress calls to see if that would help, the script still hangs at the end.

Here are the last lines of one occurance:

```
<![LOG[[Post-Installation] :: Closing the installation progress dialog.]LOG]!><time="00:38:02.02760" date="03-26-2024" component="Close-InstallationProgress" context="NT-AUTORITÄT\SYSTEM" type="1" thread="8772" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Closing the installation progress dialog's runspace.]LOG]!><time="00:38:02.06560" date="03-26-2024" component="Close-InstallationProgress" context="NT-AUTORITÄT\SYSTEM" type="1" thread="8772" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: regioiT_Windows11DKI_1.0.0.0_DEU_x64_R3 Installation completed with exit code [0].]LOG]!><time="00:38:02.22660" date="03-26-2024" component="Exit-Script" context="NT-AUTORITÄT\SYSTEM" type="1" thread="8772" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: -------------------------------------------------------------------------------]LOG]!><time="00:38:02.24560" date="03-26-2024" component="Exit-Script" context="NT-AUTORITÄT\SYSTEM" type="1" thread="8772" file="Deploy-Application.ps1">

```

**Comment by mjr4077au** [comment] 2024-03-26 01:24
This is already addressed in `develop` with https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/d1d41413c4f1b1ad2f8e7752fb15ce66b5346b12 and https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/f71708d006b56e308e9237bfdbeabdf81771a0a9.
