### ISSUE TITLE
Show-InstallationPrompt Scaling Issue

### ISSUE THREAD

**Issue by simondettling** [PSAppDeployToolkit/PSAppDeployToolkit#345] opened 2018-04-16 13:55 UTC
I'm having some weird scaling issues with "Show-InstallationPrompt" on Windows 10 Devices, where the Display Scaling value in the Settings App is set to a Value greater than 100%. Here in this example, a Scaling Value of 150% is being used.

The Scaling Issue only happens when "Show-InstallationProgress" is being used previously.

As an example, I'm using the following Lines of PoSh within Deploy-Application.ps1

`Show-InstallationPrompt -Message "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.`n`nStet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`n`nLorem ipsum dolor sit amet, consetetur sadipscing elitr." -ButtonMiddleText "Next"`

`Show-InstallationProgress`

` Show-InstallationPrompt -Message "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.`n`nStet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.`n`nLorem ipsum dolor sit amet, consetetur sadipscing elitr." -ButtonMiddleText "Next"`

Edit: The misformatted "n" above should be a new line in PowerShell.

The result is the following:

<img width="339" alt="1" src="https://user-images.githubusercontent.com/38430400/38813003-12e9b4ea-418e-11e8-9ca1-6dec56a833f3.PNG">

<img width="332" alt="2" src="https://user-images.githubusercontent.com/38430400/38813009-17a95b70-418e-11e8-905c-ea2066173cf8.PNG">

<img width="226" alt="3" src="https://user-images.githubusercontent.com/38430400/38813017-1d2ffbbc-418e-11e8-8767-c43f80d50ff7.PNG">

As you can see, the first Prompt looks normal, even though it is slightly blurred. However the last prompt, which was called exactly as the first prompt after Show-InstallationProgress, scales wrong for some reason, resulting in text cut offs.

**Comment by sintaxasn** [comment] 2018-11-06 20:13
This issue was moved to https://discourse.psappdeploytoolkit.com/t/show-installationprompt-scaling-issue/1146

**Comment by simondettling** [comment] 2019-10-03 08:11
Any updates on this? I can still reproduce this on 3.8.0. Thanks.

**Comment by luki1412** [comment] 2020-05-29 07:01
Cannot reproduce on the latest build so this should be fixed. The window now scales with text.
Will be a part of the release 3.8.3

**Closed** 2020-06-03 08:40 UTC
Labels: bug, resolved/implemented
