### ISSUE TITLE
Request to extend Show-InstallationWelcome -CloseApps

### ISSUE THREAD

**Issue by AcidUser85** [PSAppDeployToolkit/PSAppDeployToolkit#110] opened 2015-11-04 14:23 UTC
Hello,

Currently there is an option to block execution.
But it affects all executables specified for "-closeapps"
Often some processes of application are started during install or uninstall.
So would be nice to have possibility to block only specific processes, but not all and at the same time possibility to close all of them.

For example for java:

Show-InstallationWelcome -CloseApps 'iexplore,firefox,chrome,javaw.exe' -CloseAppsCountdown 3600 -BlockExecution -PersistPrompt

This closes and blocks web browsers and "javaw.exe" (running java applications), BUT!
But when you install java, installer starts "javaw.exe " process, which produces unwanted pop-up message about blocked application. But this feature is intended to show this message when USER tries to run application, but not the installer. So we would want to make exceptions of what to block and what just close before running installer.

So that enhancement could look like this:

Show-InstallationWelcome -CloseApps 'iexplore,firefox,chrome,javaw.exe' -CloseAppsCountdown 3600 -BlockExecution 'iexplore,firefox,chrome' -PersistPrompt

Here would we prevent user from running web browsers, close conflicting apps (including java applications javaw.exe processes) and let the installer start javaw.exe process without unwanted blocked app pop-ups.

**Comment by amotaz** [comment] 2015-11-08 22:29
For now you can Call Show-InstallationWelcome with only the -closeapps parameter, then afterwards call the Block-AppExecution function to specify different applications to block. We'll look towards maybe adding this functionality to Show-InstallationWelcome in a future major version.

**Comment by sintaxasn** [comment] 2018-11-06 20:19
This issue was moved to https://discourse.psappdeploytoolkit.com/t/request-to-extend-show-installationwelcome-closeapps/1236

**Comment by mjr4077au** [comment] 2024-10-14 05:46
Closing as a duplicate of #81. I can appreciate the request is nearly a decade old, it's not forgotten though!

**Closed by mjr4077au** 2024-10-14 05:46 UTC
Labels: Type: Idea / Enhancement
