### ISSUE TITLE
Get-InstalledApplication	+ Execute-MSI

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#495] opened 2020-05-06 10:07 UTC
Since last update big problems with Get-InstalledApplication + Execute-MSI:

We using GUID Variables + Names in Script

```
# V5
		# Uninstall eA-Diagnostics-SupportTools_V5 3.5.0.30
		Execute-MSI -Action Uninstall -Path '{FF8BFF83-256C-4D57-8AD6-15784F667549}'
		# Uninstall eA-Diagnostics_V5 3.5.0.30
		Execute-MSI -Action Uninstall -Path '{FE2E3908-F474-4C3B-8085-AEE3436E180E}'
	# V6
		# Uninstall eA-Diagnostics_-SupportTools_V6 3.6.1.8
		Execute-MSI -Action Uninstall -Path '{BB6038BF-790A-44AF-9672-2A8261832748}'
		# Uninstall eADiagnostics-Support Tools_V6 3.6.3.11
		Execute-MSI -Action Uninstall -Path '{A79ED3E4-0FF7-46F4-A3B6-82F4AD8EC753}'
		# Uninstall eA-Diagnostics_V6 3.6.0.21
		Execute-MSI -Action Uninstall -Path '{E5CA0307-2CC5-4FAB-BF8A-CF0FB482A84D}'
	# V7
		# Uninstall eA-Diagnostics-SupportTools_V7 3.7.0.21
		Execute-MSI -Action Uninstall -Path '{0462239E-FA73-4C88-8BD1-D0E646356E62}'
		# Uninstall eA-Diagnostics-SupportTools_V7 3.7.1.3
		Execute-MSI -Action Uninstall -Path '{3D947FA7-679D-47AA-93D3-090AAB6EDA82}'
		# Uninstall eA-Diagnostics-SupportTools_V7 3.7.2.14
		Execute-MSI -Action Uninstall -Path '{34AD1F89-B88D-4376-99F1-9CD9DDC13CD8}'
		# Uninstall eA-Diagnostics-SupportTools_V7 3.7.3.9
		Execute-MSI -Action Uninstall -Path '{F7391C13-BA92-4BCB-A929-FE27A791EDBF}'
		# Uninstall eA-Diagnostics-SupportTools_V7 3.7.4.9
		Execute-MSI -Action Uninstall -Path '{6969737C-ABB9-4864-B8C4-071E7EBDE30D}'
		# Uninstall eA_DiagnosticsSupportTool_v7.5 3.7.5.10
		Execute-MSI -Action Uninstall -Path '{5375809A-EDB6-465A-BAD2-2602A62C4F02}'
		# Uninstall eA-Diagnostics_V7 3.7.0.21
		Execute-MSI -Action Uninstall -Path '{D475C6BC-F41D-47A3-B9F0-7962AB8D7A78}'
	# V8
		# Uninstall eA_DiagnosticsSupportTool_v8 3.8.6.5
		Execute-MSI -Action Uninstall -Path '{AB0F44B3-829E-492E-AC01-A422CD6346BB}'
		# Uninstall eA_Diagnostics_V8 3.8.x
		Execute-MSI -Action Uninstall -Path '{F968E8AC-90D6-4765-BD2E-187FA9CFA7EC}'
	# V9
		# Uninstall eA_Diagnostics_SQL2014_Compatibility_Patch
		Execute-MSI -Action Uninstall -Path '{7B15E7CA-D3D4-4748-8662-477F71BDBF48}'
		# Uninstall eA_DiagnosticsSupportTool_v9 3.9.x gleicher Product code
		Execute-MSI -Action Uninstall -Path '{6CF8A63E-E1EB-476C-BF00-A425D5017E5B}'
		# Uninstall eA_Diagnostics_V9 3.9.x
		Execute-MSI -Action Uninstall -Path '{AB0F44B3-829E-492E-AC01-A422CD6346BB}'
	
	# V10
		# Uninstall eA_DiagnosticsSupportTool_v10 3.10.x.x
		Execute-MSI -Action Uninstall -Path '{6DD3B517-EF5E-40F1-ABA3-F0B6B4BB677A}'
		# Uninstall eA_Diagnostics_V10 3.10.x.x
		Execute-MSI -Action Uninstall -Path '{BB93207A-E3CF-4C86-81AE-CD196B14A0AC}'
		
	# V11
		# Uninstall eA_DiagnosticsSupportTool_v11 1.1.x.x
		Execute-MSI -Action Uninstall -Path '{6627E87C-DB36-4151-9528-7C8EC62D839E}'
		# Uninstall eA_DiagnosticsSupportTool_v11 1.2.x.x
		Execute-MSI -Action Uninstall -Path '{ED1054AD-6453-42D2-AA27-E22611FD8990}'
		# Uninstall eA_Diagnostics_V11 1.1.x.x
		Execute-MSI -Action Uninstall -Path '{8344FC14-84FC-44B8-B66F-5C97211D3248}'
	# V12
		# Uninstall eA_DiagnosticsSupportTool_v12 1.1.x.x
		Execute-MSI -Action Uninstall -Path '{EFF754E6-D39A-4CCE-BC69-302FF3044EA7}'
		#Uninstall eA_Diagnostic_v12 1.1.x.x
		Execute-MSI -Action Uninstall -Path '{2FA2FC5F-8F54-45BA-894D-44FFEF3ACD73}'

		
	#Remove Unknown GUIDS
		Remove-MSIApplications -Name 'eA_Diagnostics'
		Remove-MSIApplications -Name 'eA_DiagnosticsSupportTool'
```

The old Version (3.8.1) searching for installed applications very fast. The new (3.8.2) needs very long time for each GUID. after 120 mins SCCM gets an Time Out 
I think there is the problem with this part:

[Pre-Installation] :: Get information for installed Product Code [{FF8BFF83-256C-4D57-8AD6-15784F667549}]... 

Needs 20 seconds!!

 Skipped 3 entries while searching, because they were considered Microsoft updates.

Logs are attached

[KPMG_eAudIT-Diagnostics_12.1.4.3_x64_DE_01_06-05-2020_Install_New_Wrapper.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/4586073/KPMG_eAudIT-Diagnostics_12.1.4.3_x64_DE_01_06-05-2020_Install_New_Wrapper.log)
[KPMG_eAudIT-Diagnostics_12.1.4.3_x64_DE_01_06-05-2020_Install_Old_Wrapper.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/4586074/KPMG_eAudIT-Diagnostics_12.1.4.3_x64_DE_01_06-05-2020_Install_Old_Wrapper.log)
[AppEnforce.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/4586075/AppEnforce.log)

**Comment by cyborgrd** [comment] 2020-05-06 10:22
In attachment is the code difference that cause the issue

![diff](https://user-images.githubusercontent.com/16757493/81166668-29f3d980-8f94-11ea-9295-c911be9c18e9.PNG)

**Comment by redcrossevvy** [comment] 2020-05-06 10:23
I am having the same experience; especially the, “Skipped 3 entries while searching, because they were considered Microsoft updates,” message.


On May 6, 2020, at 6:07 AM, cyborgrd <notifications@github.com> wrote:

﻿

Since last update big problems with Get-InstalledApplication + Execute-MSI:

We using GUID Variables + Names in Script

# V5
                # Uninstall eA-Diagnostics-SupportTools_V5 3.5.0.30
                Execute-MSI -Action Uninstall -Path '{FF8BFF83-256C-4D57-8AD6-15784F667549}'
                # Uninstall eA-Diagnostics_V5 3.5.0.30
                Execute-MSI -Action Uninstall -Path '{FE2E3908-F474-4C3B-8085-AEE3436E180E}'
        # V6
                # Uninstall eA-Diagnostics_-SupportTools_V6 3.6.1.8
                Execute-MSI -Action Uninstall -Path '{BB6038BF-790A-44AF-9672-2A8261832748}'
                # Uninstall eADiagnostics-Support Tools_V6 3.6.3.11
                Execute-MSI -Action Uninstall -Path '{A79ED3E4-0FF7-46F4-A3B6-82F4AD8EC753}'
                # Uninstall eA-Diagnostics_V6 3.6.0.21
                Execute-MSI -Action Uninstall -Path '{E5CA0307-2CC5-4FAB-BF8A-CF0FB482A84D}'
        # V7
                # Uninstall eA-Diagnostics-SupportTools_V7 3.7.0.21
                Execute-MSI -Action Uninstall -Path '{0462239E-FA73-4C88-8BD1-D0E646356E62}'
                # Uninstall eA-Diagnostics-SupportTools_V7 3.7.1.3
                Execute-MSI -Action Uninstall -Path '{3D947FA7-679D-47AA-93D3-090AAB6EDA82}'
                # Uninstall eA-Diagnostics-SupportTools_V7 3.7.2.14
                Execute-MSI -Action Uninstall -Path '{34AD1F89-B88D-4376-99F1-9CD9DDC13CD8}'
                # Uninstall eA-Diagnostics-SupportTools_V7 3.7.3.9
                Execute-MSI -Action Uninstall -Path '{F7391C13-BA92-4BCB-A929-FE27A791EDBF}'
                # Uninstall eA-Diagnostics-SupportTools_V7 3.7.4.9
                Execute-MSI -Action Uninstall -Path '{6969737C-ABB9-4864-B8C4-071E7EBDE30D}'
                # Uninstall eA_DiagnosticsSupportTool_v7.5 3.7.5.10
                Execute-MSI -Action Uninstall -Path '{5375809A-EDB6-465A-BAD2-2602A62C4F02}'
                # Uninstall eA-Diagnostics_V7 3.7.0.21
                Execute-MSI -Action Uninstall -Path '{D475C6BC-F41D-47A3-B9F0-7962AB8D7A78}'
        # V8
                # Uninstall eA_DiagnosticsSupportTool_v8 3.8.6.5
                Execute-MSI -Action Uninstall -Path '{AB0F44B3-829E-492E-AC01-A422CD6346BB}'
                # Uninstall eA_Diagnostics_V8 3.8.x
                Execute-MSI -Action Uninstall -Path '{F968E8AC-90D6-4765-BD2E-187FA9CFA7EC}'
        # V9
                # Uninstall eA_Diagnostics_SQL2014_Compatibility_Patch
                Execute-MSI -Action Uninstall -Path '{7B15E7CA-D3D4-4748-8662-477F71BDBF48}'
                # Uninstall eA_DiagnosticsSupportTool_v9 3.9.x gleicher Product code
                Execute-MSI -Action Uninstall -Path '{6CF8A63E-E1EB-476C-BF00-A425D5017E5B}'
                # Uninstall eA_Diagnostics_V9 3.9.x
                Execute-MSI -Action Uninstall -Path '{AB0F44B3-829E-492E-AC01-A422CD6346BB}'

        # V10
                # Uninstall eA_DiagnosticsSupportTool_v10 3.10.x.x
                Execute-MSI -Action Uninstall -Path '{6DD3B517-EF5E-40F1-ABA3-F0B6B4BB677A}'
                # Uninstall eA_Diagnostics_V10 3.10.x.x
                Execute-MSI -Action Uninstall -Path '{BB93207A-E3CF-4C86-81AE-CD196B14A0AC}'

        # V11
                # Uninstall eA_DiagnosticsSupportTool_v11 1.1.x.x
                Execute-MSI -Action Uninstall -Path '{6627E87C-DB36-4151-9528-7C8EC62D839E}'
                # Uninstall eA_DiagnosticsSupportTool_v11 1.2.x.x
                Execute-MSI -Action Uninstall -Path '{ED1054AD-6453-42D2-AA27-E22611FD8990}'
                # Uninstall eA_Diagnostics_V11 1.1.x.x
                Execute-MSI -Action Uninstall -Path '{8344FC14-84FC-44B8-B66F-5C97211D3248}'
        # V12
                # Uninstall eA_DiagnosticsSupportTool_v12 1.1.x.x
                Execute-MSI -Action Uninstall -Path '{EFF754E6-D39A-4CCE-BC69-302FF3044EA7}'
                #Uninstall eA_Diagnostic_v12 1.1.x.x
                Execute-MSI -Action Uninstall -Path '{2FA2FC5F-8F54-45BA-894D-44FFEF3ACD73}'


        #Remove Unknown GUIDS
                Remove-MSIApplications -Name 'eA_Diagnostics'
                Remove-MSIApplications -Name 'eA_DiagnosticsSupportTool'


The old Version (3.8.1) searching for installed applications very fast. The new (3.8.2) needs very long time for each GUID. after 120 mins SCCM gets an Time Out
I think there is the problem with this part:

[Pre-Installation] :: Get information for installed Product Code [{FF8BFF83-256C-4D57-8AD6-15784F667549}]...

Needs 20 seconds!!

Skipped 3 entries while searching, because they were considered Microsoft updates.

Logs are attached

KPMG_eAudIT-Diagnostics_12.1.4.3_x64_DE_01_06-05-2020_Install_New_Wrapper.log<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Ffiles%2F4586073%2FKPMG_eAudIT-Diagnostics_12.1.4.3_x64_DE_01_06-05-2020_Install_New_Wrapper.log&data=02%7C01%7Cevelyn.vose%40redcross.org%7C6d55b57b26324f4754b608d7f1a54c0e%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637243564559565250&sdata=Fk2rEZN7ZSETGfuRJ%2FV5FPix3eno1N8Wk48JjwyQ66o%3D&reserved=0>
KPMG_eAudIT-Diagnostics_12.1.4.3_x64_DE_01_06-05-2020_Install_Old_Wrapper.log<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Ffiles%2F4586074%2FKPMG_eAudIT-Diagnostics_12.1.4.3_x64_DE_01_06-05-2020_Install_Old_Wrapper.log&data=02%7C01%7Cevelyn.vose%40redcross.org%7C6d55b57b26324f4754b608d7f1a54c0e%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637243564559575206&sdata=5nb%2FLMryj%2FsULet2PbxQz8NM5S6pjSWITxmS19wXTnQ%3D&reserved=0>
AppEnforce.log<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Ffiles%2F4586075%2FAppEnforce.log&data=02%7C01%7Cevelyn.vose%40redcross.org%7C6d55b57b26324f4754b608d7f1a54c0e%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637243564559575206&sdata=Z5Y7QPLH90O3LgSHvr2dOQvGiZNz7%2Ftcc2mIadnU3yY%3D&reserved=0>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSAppDeployToolkit%2FPSAppDeployToolkit%2Fissues%2F495&data=02%7C01%7Cevelyn.vose%40redcross.org%7C6d55b57b26324f4754b608d7f1a54c0e%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637243564559585161&sdata=jPS%2FaSNz9lGVVuLccqx6jG3C7WCq9Y1CGm1NitWs%2BHI%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFSZPPZPBWNTBPQXHQ6KYTRQEZGLANCNFSM4M2J2K3Q&data=02%7C01%7Cevelyn.vose%40redcross.org%7C6d55b57b26324f4754b608d7f1a54c0e%7Cdd5b5d42c0d34ad2b5f160edb3af2771%7C0%7C0%7C637243564559585161&sdata=yPbJ9%2BJmy%2Few0rlnm%2F5WypTKzuEjmXFVEqXATszW9pk%3D&reserved=0>.

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

**Comment by luki1412** [comment] 2020-05-06 11:14
V 3.8.2 is not released yet. 3.8.1 came with the changes to the function.

I have a possible candidate for these slowdowns. I need to do some tests.

**Comment by luki1412** [comment] 2020-05-07 17:28
It is caused by Remove-FilenameChars inside. The function itself isn't slow but it adds up when going through all those strings multiple times.

**Comment by luki1412** [comment] 2020-05-09 14:38
Resolved in the latest version.

**Closed by luki1412** 2020-05-09 14:38 UTC
Labels: bug, resolved/implemented
