### ISSUE TITLE
Update Welcome Message Text Based on Deployment Type

### ISSUE THREAD

**Issue by Xengrath** [PSAppDeployToolkit/PSAppDeployToolkit#588] opened 2020-11-29 23:49 UTC
If you run an interactive uninstall of a package, there are certain words that should update depending on the DeploymentType.

### **DeploymentType_Install:**
- The following programs must be closed before the **installation** can proceed.
- The following application is about to be **installed**:
- You can choose to defer the **installation** until the deferral expires

### **DeploymentType_UnInstall:**
- The following programs must be closed before the **uninstallation** can proceed.
- The following application is about to be **uninstalled**:
- You can choose to defer the **uninstallation** until the deferral expires

### **DeploymentType_Repair:**
- The following programs must be closed before the **repair** can proceed.
- The following application is about to be **repaired**:
- You can choose to defer the **repair** until the deferral expires

**Comment by mjr4077au** [comment] 2024-10-14 10:53
Duplicate of #41.

**Closed by mjr4077au** 2024-10-14 10:53 UTC
Labels: Status: Duplicate
