### ISSUE TITLE
App Deployment toolkit crashes on touch enabled windows 7 devices

### ISSUE THREAD

**Issue by alexverboon** [PSAppDeployToolkit/PSAppDeployToolkit#56] opened 2015-06-30 22:19 UTC
Hello all
Just wanted to make you aware of an Issue we are currently experiencing with running the app deployment toolkit on touch enabled windows 7 devices. due to ole32.dll. The result is that powershell crashes. We have an open case with MS...their current argument is that powershell wasnt designed to create gui's

I will share more details later but thought i let you know.

**Comment by mmashwani** [comment] 2015-07-01 15:24
Thanks for reporting. That's kind of a BS answer from Microsoft support.

**Comment by mmashwani** [comment] 2015-07-24 02:54
@alexverboon 
Was your case with MS ever resolved to your satisfaction? Did they provide a fix of any sort?

**Comment by alexverboon** [comment] 2015-07-24 07:48
Hi
No unfortunately not. I have escalated the case and its now as we don't accept their statement that you should not create GUI with PowerShell. Also it only happens when the devices are touch screen enabled.
Keep you posted 

-----Original Message-----

**Comment by mmashwani** [comment] 2015-07-31 18:31
@alexverboon Hi, I saw the message you sent Dan regarding this issue and the response you received from MS. I was wondering if you could test something out for me to see if it resolves your issue.

Can you add this to the start of the PS script and see if it makes a difference?:
$Host.Runspace.ThreadOptions = 'ReuseThread'

**Comment by seanlillis** [comment] 2015-07-31 21:26
@alexverboon I've got a Lenovo S540 touchscreen, I haven't seen this issue running the toolkit on my machine. You mentioned in your mail that the crash happens directly after running Execute-Process Setup.exe. Does this happen with any other deployment scripts on those machines under the same circumstances? Is there any evidence that points to WPF causing the conflict (Show-InstallationProgress)? Are there any dynamic updates to the progress message during the installation that look to be triggering the crash? Can you share the script and log file?

**Comment by alexverboon** [comment] 2015-07-31 22:27
Hi Sean
Will ask my colleagues who where troubleshooting this to share the details and debug logs.

Alex 

-----Original Message-----

**Comment by mreinli** [comment] 2015-08-05 13:53
@mmashwani: we added `$Host.Runspace.ThreadOptions = 'ReuseThread'` to the start of the script without seeing any different behavior. PowerShell is still crashing caused by ole32.dll.

@seanlillis: we are updating the status message created with `Show-InstallationProgress` multiple times during the installation.
 
It is possible to reproduce the issue with a special crafted AppDeployToolkit script that only displays a Show-InstallationProgress WPF status messages and then waits. After a while the PowerShell process crashes. 
The problem initially occured on systems running .NET Framework 4.5 (4.0.30319.18444) but it also occurs on machines with a fully patched .NET Framework 4.5.2 (4.0.30319.36301).

> Faulting application name: powershell.exe, version: 6.2.9200.16398, time stamp: 0x50337c74
> Faulting module name: ole32.dll, version: 6.1.7601.23118, time stamp: 0x559821fc
> Exception code: 0xc0000005
> Fault offset: 0x0000000000029c91
> Faulting process id: 0x1b5c
> Faulting application start time: 0x01d0cf5fb5b56911
> Faulting application path: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
> Faulting module path: C:\WINDOWS\system32\ole32.dll

If the PowerShell process is running under a user account it works fine. It only crashes when PowerShell.exe runs under the SYSTEM account (which is the case when executing the script with Configuration Manager).

Microsoft latest statement is that WPF is not supported in session 0. They are referring to this KB article: https://msdn.microsoft.com/en-us/library/bb613549%28v=vs.90%29.aspx

> The use of WPF to build Windows services is unsupported. Because WPF is a presentation technology, the Windows service requires the appropriate permissions to perform visual operations that involve user interaction. If the Windows service does not have the appropriate permissions, there may be unexpected results.

**Comment by mmashwani** [comment] 2015-08-05 14:55
The toolkit is designed so that it never tries to run any of the WPF GUI elements in session 0. The only way to get the toolkit to run the WPF GUI elements is by using something like serviceui.exe so that the toolkit is forced to break out of session 0 and display the GUI elements in a user session. Are you using something like this in your deployments?

Also, you mention that the crash happens after a call to Execute-Process. Can you share what your Execute-Process command looks like? Are you running this command so that the setup.exe is executed silently? Could the problem be that setup.exe is trying to display a GUI in session 0 and this causes the crash?

**Comment by mreinli** [comment] 2015-08-19 11:00
We do not use ServiceUI.exe. We use the setting "Allow user to interact with the installation" and "Only install when a user is logged on" (as otherwise the first option is not available) to display the GUI. The Execute-Process has nothing to do with the crash as it also happens when we run a script that only displays a status message.

I am a bit confused. If we run the toolkit with "Allow user to interact" and "Only install when a user is logged on", in which session does the GUI elements are actually running?

**Comment by mmashwani** [comment] 2015-08-19 12:39
The GUI elements would run in the session the user is running in.

**Comment by evensen007** [comment] 2015-11-12 19:56
I just ran into this issue; was anyone ever able to find a resolution? This is terribly broken, as it prevent us from deploying powershell script based applications to our large laptop fleet that is touch enabled. Any update would be appreciated!

**Comment by alexverboon** [comment] 2015-11-18 16:18
Hello, my coleague Marco wil provide an update on this, we've going through
a very very lenghty case with MS.

On Thu, Nov 12, 2015 at 8:56 PM, evensen007 <notifications@github.com>
wrote:

> I just ran into this issue; was anyone ever able to find a resolution?
> This is terribly broken, as it prevent us from deploying powershell script
> based applications to our large laptop fleet that is touch enabled. Any
> update would be appreciated!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/56#issuecomment-156217083>
> .
>



-- 
Alex Verboon
www.verboon.info

**Comment by evensen007** [comment] 2015-11-20 14:02
I look forward to this Alex! This severely effects powershell scripted deployments to Win7 touch devices!

**Comment by mreinli** [comment] 2015-11-30 14:47
Hi evensen007,
as a workaround we disabled the touchscreen in device manager during the installation:
```
If ($T450s) {
    $DeviceID = "USB\VID_04F3&PID_0418*"
    Execute-Process -FilePath "cmd.exe" -Arguments "/c $dirSupportFiles\devcon.exe disable `"$DeviceID`"" -ContinueOnError $true
}

DO THINGS

If ($T450s) {
    $DeviceID = "USB\VID_04F3&PID_0418*"
    Execute-Process -FilePath "cmd.exe" -Arguments "/c $dirSupportFiles\devcon.exe enable `"$DeviceID`"" -ContinueOnError $true
}
```
@mmashwani when I look at the function Show-InstallationProgress I do not see anything that invokes the WPF in the user session. Can you please elaborate a bit how this works. Also Microsoft Premier Support came to the conclusion that it is running in session 0 (based on the logs we submitted).

I try to get a statement from Microsoft which I can share with you.

**Comment by appPackager** [comment] 2015-12-08 19:09
We are also seeing this issue at my company on Windows 7 x64 touchscreen-enabled laptops.  Within application event logs we see the powershell.exe crash referencing ole32.dll.  We have reimaged a Windows 7 touchscreen-enabled laptop which experienced the issue with Windows 8 x64 and Windows 10 x64. The problem does NOT appear to occur for Windows 8 x64 nor Windows 10 x64.  If the opportunity arises would one of the PSAppDeployToolkit developers be interested in joining us in a conference call with Microsoft?

**Comment by mmashwani** [comment] 2015-12-08 19:40
What if we just put in a check with Win 7 and check if it's a touch enabled device - if true, stop the touch service before we display any UI elements?

Can you manually test this on your end to see if it works? Disable the touch service (I'm not sure which one it is so you will have to share that with me), then run the toolkit to see if the issue goes away.

**Comment by appPackager** [comment] 2015-12-09 20:19
Speaking for my company I can say that temporarily disabling the touchscreen hardware during the course of displaying UI messages will not be acceptable because it counts on the installation process to re-enable it afterwards which can be risky and potentially generate support tickets.  

Temporarily stopping a service would be a better alternative since a user could always reboot the computer to re-enable a touchscreen, however, I don't see any services related to touchscreen on a laptop.

For the incident we just opened with Microsoft we tried a different approach of asking for an explanation as to why the displaying of the UI progress bar works on Windows 8 & 10 touchscreen under session 0 and not Windows 7.  We received a response back today so I am adding to this issue thread with the hope that this may point somebody in a direction which leads to either a PSAppDeployToolkit fix or acceptable workaround.

Microsoft's response:
"SCCM runs software as either the logged on user or as System.  When ‘Run as Administrator’ is used, which is most common, we have to run as the System account. For Windows 7, this always ends up in Session 0.  Starting in Windows 8, we introduced Session 0 Isolation as a security enhancement, so the processes run differently on Windows 8 and above.  This was a major architectural change to the Operating System so there is no way that we can back-port this to Windows 7.  With this being the case, as only touch enabled devices are affected and since Windows team has already confirmed that they do not support WPF code in Session 0, the only solution is to avoid running Windows 7 on touch enabled devices."

Microsoft also supplied these links:
https://msdn.microsoft.com/en-us/library/windows/hardware/dn653293(v=vs.85).aspx
http://blogs.technet.com/b/askperf/archive/2007/04/27/application-compatibility-session-0-isolation.aspx

**Comment by mmashwani** [comment] 2015-12-09 20:29
So is WPF specifically the problem on Win7? If we created a similar progress bar using WinForms, can they confirm if that will work?

**Comment by appPackager** [comment] 2015-12-09 22:49
Microsoft states that changing the Show-InstallationProgress function from WPF to Windows Forms should work, however, they also state that would be a step backwards. 

There may be a better option.... Just a few minutes ago I stripped out some of the bells and whistles from the Show-InstallationProgress WPF xml and it appears that powershell.exe is no longer crashing.  I am going to do some more investigation and see if I can isolate which line(s) of code within the WPF is causing the crashing.

**Comment by appPackager** [comment] 2015-12-10 19:03
Stripping out the bells and whistles from Show-InstallationProgress did NOT work. My results were skewed somehow by the state of the machine.  After a reboot the Show-InstallationProgress UI continued to crash using my modified code.

I agree now that a Windows Forms version of Show-InstallationProgress function is needed which is executed in place of the WPF Show-InstallationProgress when Windows 7 touch-enabled computers are detected. 

My personal preference is to keep the WPF version of the Show-InstallationProgress since it works on Windows 8 and newer operating systems.  At some point Windows 7 will be out-of-support so a decision can be made at that time as to whether the Windows Forms version of the Show-InstallationProgress needs to be retired.

**Comment by appPackager** [comment] 2015-12-22 22:02
I ended up creating two new functions: Show-AltInstallationProgress & Close-AltInstallationProgress which utilize Windows Forms instead of WPF. I included these two functions in my AppDeployToolkitExtensions.ps1.  

I also copied the Show-InstallationProgress & Close-InstallationProgress functions (found in AppDeployToolkitMain.ps1) to my AppDeployToolkitExtensions.ps1 then added checks for OS=6.1 (Windows 7) & 'TabletInputService'='automatic'. If those checks result in $true then the 'Alt' WinForm versions are executed instead of the WPF functions.

Since the AppDeployToolkitExtensions.ps1 is the last to load then the altered versions of Show-InstallationProgress & Close-InstalledProgress are executed in place of the original versions found in AppDeployToolkitMain.ps1. So now when the Show-InstallationProgress function is executed all the work to determine which progressbar to launch is done behind the scenes.  This is a great workaround until the programmers can incorporate a WinForm version of the installation progress to resolve the WPF crashing problem on Win 7 touch-enabled devices.

BTW: The Show-AltInstallationProgress function references a 'spiffygif_30x30.gif' animated GIF which needs to be included in your AppDeployToolkit folder. I generated it from http://spiffygif.com/

![spiffygif_30x30](https://cloud.githubusercontent.com/assets/12298202/11967023/4231e75e-a8c5-11e5-8dc8-4e267cac949b.gif)


```
#region Function Show-InstallationProgress
Function Show-InstallationProgress {
<#
.SYNOPSIS
	Displays a progress dialog in a separate thread with an updateable custom message.
.DESCRIPTION
	Create a WPF window in a separate thread to display a marquee style progress ellipse with a custom message that can be updated.
	The status message supports line breaks.
	The first time this function is called in a script, it will display a balloon tip notification to indicate that the installation has started (provided balloon tips are enabled in the configuration).
.PARAMETER StatusMessage
	The status message to be displayed. The default status message is taken from the XML configuration file.
.PARAMETER WindowLocation
	The location of the progress window. Default: just below top, centered.
.PARAMETER TopMost
	Specifies whether the progress window should be topmost. Default: $true.
.EXAMPLE
	Show-InstallationProgress
	Uses the default status message from the XML configuration file.
.EXAMPLE
	Show-InstallationProgress -StatusMessage 'Installation in Progress...'
.EXAMPLE
	Show-InstallationProgress -StatusMessage "Installation in Progress...`nThe installation may take 20 minutes to complete."
.EXAMPLE
	Show-InstallationProgress -StatusMessage 'Installation in Progress...' -WindowLocation 'BottomRight' -TopMost $false
.NOTES
.LINK
	http://psappdeploytoolkit.codeplex.com
#>
	[CmdletBinding()]
	Param (
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[string]$StatusMessage = $configProgressMessageInstall,
		[Parameter(Mandatory=$false)]
		[ValidateSet('Default','BottomRight')]
		[string]$WindowLocation = 'Default',
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[boolean]$TopMost = $true
	)
	
		
	Begin {
		## Get the name of this function and write header
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
	}
		
	Process {
		## If Windows 7 OS & touchscreen service is started then use Windows Forms version of progress screen instead of WPF (which crashes)
		If (((Get-ServiceStartMode -Name 'TabletInputService') -eq 'Automatic') -And ($($envOS.Version).substring(0,3) -eq '6.1')) { 
			Show-AltInstallationProgress -StatusMessage $StatusMessage -TopMost $TopMost
		}
		Else { 
			If ($deployModeSilent) { Return }
		
			## If the default progress message hasn't been overridden and the deployment type is uninstall, use the default uninstallation message
			If (($StatusMessage -eq $configProgressMessageInstall) -and ($deploymentType -eq 'Uninstall')) {
				$StatusMessage = $configProgressMessageUninstall
			}
		
			If ($envHost.Name -match 'PowerGUI') {
				Write-Log -Message "$($envHost.Name) is not a supported host for WPF multithreading. Progress dialog with message [$statusMessage] will not be displayed." -Severity 2 -Source ${CmdletName}
				Return
			}
		
			## Check if the progress thread is running before invoking methods on it
			If ($global:ProgressSyncHash.Window.Dispatcher.Thread.ThreadState -ne 'Running') {
				#  Notify user that the software installation has started
				$balloonText = "$deploymentTypeName $configBalloonTextStart"
				Show-BalloonTip -BalloonTipIcon 'Info' -BalloonTipText $balloonText
				#  Create a synchronized hashtable to share objects between runspaces
				$global:ProgressSyncHash = [hashtable]::Synchronized(@{ })
				#  Create a new runspace for the progress bar
				$global:ProgressRunspace = [runspacefactory]::CreateRunspace()
				$global:ProgressRunspace.ApartmentState = 'STA'
				$global:ProgressRunspace.ThreadOptions = 'ReuseThread'
				$global:ProgressRunspace.Open()
				#  Add the sync hash to the runspace
				$global:ProgressRunspace.SessionStateProxy.SetVariable('progressSyncHash', $global:ProgressSyncHash)
				#  Add other variables from the parent thread required in the progress runspace
				$global:ProgressRunspace.SessionStateProxy.SetVariable('installTitle', $installTitle)
				$global:ProgressRunspace.SessionStateProxy.SetVariable('windowLocation', $windowLocation)
				$global:ProgressRunspace.SessionStateProxy.SetVariable('topMost', [string]$topMost)
				$global:ProgressRunspace.SessionStateProxy.SetVariable('appDeployLogoBanner', $appDeployLogoBanner)
				$global:ProgressRunspace.SessionStateProxy.SetVariable('progressStatusMessage', $statusMessage)
				$global:ProgressRunspace.SessionStateProxy.SetVariable('AppDeployLogoIcon', $AppDeployLogoIcon)
				$global:ProgressRunspace.SessionStateProxy.SetVariable('dpiScale', $dpiScale)
			
				#  Add the script block to be executed in the progress runspace
				$progressCmd = [PowerShell]::Create().AddScript({
					[Xml.XmlDocument]$xamlProgress = @'
								<Window
								xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
								xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
								x:Name="Window" Title=""
								MaxHeight="200" MinHeight="180" Height="180"
								MaxWidth="456" MinWidth="456" Width="456" Padding="0,0,0,0" Margin="0,0,0,0"
								WindowStartupLocation = "Manual"
								Top=""
								Left=""
								Topmost=""
								ResizeMode="NoResize"
								Icon=""
								ShowInTaskbar="True" >
								<Window.Resources>
									<Storyboard x:Key="Storyboard1" RepeatBehavior="Forever">
										<DoubleAnimationUsingKeyFrames BeginTime="00:00:00" Storyboard.TargetName="ellipse" Storyboard.TargetProperty="(UIElement.RenderTransform).(TransformGroup.Children)[2].(RotateTransform.Angle)">
										<SplineDoubleKeyFrame KeyTime="00:00:02" Value="360"/>
										</DoubleAnimationUsingKeyFrames>
									</Storyboard>
								</Window.Resources>
								<Window.Triggers>
									<EventTrigger RoutedEvent="FrameworkElement.Loaded">
										<BeginStoryboard Storyboard="{StaticResource Storyboard1}"/>
									</EventTrigger>
								</Window.Triggers>
								<Grid Background="#F0F0F0">
									<Grid.RowDefinitions>
										<RowDefinition Height="50"/>
										<RowDefinition Height="100"/>
									</Grid.RowDefinitions>
									<Grid.ColumnDefinitions>
										<ColumnDefinition Width="45"></ColumnDefinition>
										<ColumnDefinition Width="*"></ColumnDefinition>
									</Grid.ColumnDefinitions>
									<Image x:Name = "ProgressBanner" Grid.ColumnSpan="2" Margin="0,0,0,0" Source=""></Image>
									<TextBlock x:Name = "ProgressText" Grid.Row="1" Grid.Column="1" Margin="0,5,45,10" Text="" FontSize="15" FontFamily="Microsoft Sans Serif" HorizontalAlignment="Center" VerticalAlignment="Center" TextAlignment="Center" Padding="15" TextWrapping="Wrap"></TextBlock>
									<Ellipse x:Name = "ellipse" Grid.Row="1" Grid.Column="0" Margin="0,0,0,0" StrokeThickness="5" RenderTransformOrigin="0.5,0.5" Height="25" Width="25" HorizontalAlignment="Right" VerticalAlignment="Center">
										<Ellipse.RenderTransform>
											<TransformGroup>
												<ScaleTransform/>
												<SkewTransform/>
												<RotateTransform/>
											</TransformGroup>
										</Ellipse.RenderTransform>
										<Ellipse.Stroke>
											<LinearGradientBrush EndPoint="0.445,0.997" StartPoint="0.555,0.003">
												<GradientStop Color="White" Offset="0"/>
												<GradientStop Color="#008000" Offset="1"/>
											</LinearGradientBrush>
										</Ellipse.Stroke>
									</Ellipse>
									</Grid>
								</Window>
'@
				
					## Set the configurable values using variables added to the runspace from the parent thread
					#  Calculate the position on the screen where the progress dialog should be placed
					$screen = [Windows.Forms.Screen]::PrimaryScreen
					$screenWorkingArea = $screen.WorkingArea
					[int32]$screenWidth = $screenWorkingArea | Select-Object -ExpandProperty Width
					[int32]$screenHeight = $screenWorkingArea | Select-Object -ExpandProperty Height
					#  Set the start position of the Window based on the screen size
					If ($windowLocation -eq 'BottomRight') {
						$xamlProgress.Window.Left = [string](($screenWidth / ($dpiScale / 100)) - ($xamlProgress.Window.Width))
						$xamlProgress.Window.Top = [string](($screenHeight / ($dpiScale / 100)) - ($xamlProgress.Window.Height))
					}
					#  Show the default location (Top center)
					Else {
						#  Center the progress window by calculating the center of the workable screen based on the width of the screen relative to the DPI scale minus half the width of the progress bar
						$xamlProgress.Window.Left = [string](($screenWidth / (2 * ($dpiScale / 100) )) - (($xamlProgress.Window.Width / 2)))
						$xamlProgress.Window.Top = [string]($screenHeight / 9.5)
					}
					$xamlProgress.Window.TopMost = $topMost
					$xamlProgress.Window.Icon = $appDeployLogoIcon
					$xamlProgress.Window.Grid.Image.Source = $appDeployLogoBanner
					$xamlProgress.Window.Grid.TextBlock.Text = $ProgressStatusMessage
					$xamlProgress.Window.Title = $installTitle
					#  Parse the XAML
					$progressReader = New-Object -TypeName System.Xml.XmlNodeReader -ArgumentList $xamlProgress
					$global:ProgressSyncHash.Window = [Windows.Markup.XamlReader]::Load($progressReader)
					$global:ProgressSyncHash.ProgressText = $global:ProgressSyncHash.Window.FindName('ProgressText')
					#  Add an action to the Window.Closing event handler to disable the close button
					$global:ProgressSyncHash.Window.Add_Closing({ $_.Cancel = $true })
					#  Allow the window to be dragged by clicking on it anywhere
					$global:ProgressSyncHash.Window.Add_MouseLeftButtonDown({ $global:ProgressSyncHash.Window.DragMove() })
					#  Add a tooltip
					$global:ProgressSyncHash.Window.ToolTip = $installTitle
					$global:ProgressSyncHash.Window.ShowDialog() | Out-Null
					$global:ProgressSyncHash.Error = $Error
				})
			
				$progressCmd.Runspace = $global:ProgressRunspace
				Write-Log -Message "Spin up progress dialog in a separate thread with message: [$statusMessage]." -Source ${CmdletName}
				#  Invoke the progress runspace
				$progressData = $progressCmd.BeginInvoke()
				#  Allow the thread to be spun up safely before invoking actions against it.
				Start-Sleep -Seconds 1
				If ($global:ProgressSyncHash.Error) {
					Write-Log -Message "Failure while displaying progress dialog. `n$(Resolve-Error -ErrorRecord $global:ProgressSyncHash.Error)" -Severity 3 -Source ${CmdletName}
				}
			}
			## Check if the progress thread is running before invoking methods on it
			ElseIf ($global:ProgressSyncHash.Window.Dispatcher.Thread.ThreadState -eq 'Running') {
				#  Allow time between updating the thread
				Start-Sleep -Seconds 1
				Write-Log -Message "Update progress message: [$statusMessage]." -Source ${CmdletName}
				#  Update the progress text
				Try {
					$global:ProgressSyncHash.Window.Dispatcher.Invoke([Windows.Threading.DispatcherPriority]'Normal', [Windows.Input.InputEventHandler]{ $global:ProgressSyncHash.ProgressText.Text = $statusMessage }, $null, $null)
				}
				Catch {
					Write-Log -Message "Unable to update the progress message. `n$(Resolve-Error)" -Severity 2 -Source ${CmdletName}
				}
			}
		}
	}
		
	End {
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
	}
}
#endregion


#region Function Close-InstallationProgress
Function Close-InstallationProgress {
<#
.SYNOPSIS
	Closes the dialog created by Show-InstallationProgress.
.DESCRIPTION
	Closes the dialog created by Show-InstallationProgress.
	This function is called by the Exit-Script function to close a running instance of the progress dialog if found.
.EXAMPLE
	Close-InstallationProgress
.NOTES
	This is an internal script function and should typically not be called directly.
.LINK
	http://psappdeploytoolkit.codeplex.com
#>
	[CmdletBinding()]
	Param (
	)
	
	Begin {
		## Get the name of this function and write header
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
	}
		
	Process {
		## If Windows 7 & touchscreen service started then use Windows Forms version of progress screen over WPF
		If (((Get-ServiceStartMode -Name 'TabletInputService') -eq 'Automatic') -And ($($envOS.Version).substring(0,3) -eq '6.1')) { 
			Close-AltInstallationProgress
		}
		Else { 
			If ($global:ProgressSyncHash.Window.Dispatcher.Thread.ThreadState -eq 'Running') {
				## Close the progress thread
				Write-Log -Message 'Close the installation progress dialog.' -Source ${CmdletName}
				$global:ProgressSyncHash.Window.Dispatcher.InvokeShutdown()
				$global:ProgressSyncHash.Clear()
			}
		}
	}
		
	End {
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
	}
}
#endregion


#region Function Show-AltInstallationProgress
Function Show-AltInstallationProgress {
<#
.SYNOPSIS
	Displays a progress dialog in a separate thread with an updateable custom message. This progress is preferred for touch enabled devices running Windows 7
.DESCRIPTION
	Create a Windows Form window in a separate thread to display a custom message that can be updated.
	The status message supports line breaks.
	The first time this function is called in a script, it will display a balloon tip notification to indicate that the installation has started (provided balloon tips are enabled in the configuration).
.PARAMETER StatusMessage
	The status message to be displayed. The default status message is taken from the XML configuration file.
.PARAMETER TopMost
	Specifies whether the progress window should be topmost. Default: $true.
.EXAMPLE
	Show-AltInstallationProgress -StatusMessage "Installation in Progress..."
.EXAMPLE
	Show-AltInstallationProgress -StatusMessage "Installation in Progress...`nThe installation may take 20 minutes to complete."
.NOTES
.LINK
	http://psappdeploytoolkit.codeplex.com
#>

	[CmdletBinding()]
	Param (
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[string]$StatusMessage = $configProgressMessageInstall,
		[Parameter(Mandatory=$false)]
		[ValidateNotNullorEmpty()]
		[boolean]$TopMost = $true
	)
	
	Begin {
		## Get the name of this function and write header
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
	}
	Process {
		If ($deployModeSilent) { Return }
		
		## If the default progress message hasn't been overridden and the deployment type is uninstall, use the default uninstallation message
		If (($StatusMessage -eq $configProgressMessageInstall) -and ($deploymentType -eq 'Uninstall')) {
			$StatusMessage = $configProgressMessageUninstall
		}
		
		If (!($AltprogressForm.Visible)) {
			#  Notify user that the software installation has started
			$balloonText = "$deploymentTypeName $configBalloonTextStart"
			Show-BalloonTip -BalloonTipIcon 'Info' -BalloonTipText $balloonText
			
			# initialize Form
			$global:AltProgressForm = New-Object System.Windows.Forms.Form
			$AltProgressForm.Text = $installTitle
			$AltProgressForm.Icon = $appDeployLogoIcon
			$AltProgressForm.MinimizeBox = $false
			$AltProgressForm.MaximizeBox = $false
			$AltProgressForm.StartPosition = "CenterScreen"
			$AltProgressForm.Name = '$installTitle'
			$AltProgressForm.TopMost = [String]$TopMost
			$AltProgressForm.DataBindings.DefaultDataSourceUpdateMode = 0
			$AltProgressForm.Size = '456,200'
			$AltProgressForm.FormBorderStyle='FixedDialog' 
			$AltProgressForm.Add_FormClosing({$_.Cancel = $true;})

			# Add logo banner
			$img = [System.Drawing.Image]::Fromfile($appDeployLogoBanner)
			$pictureBanner = New-Object Windows.Forms.Picturebox
			$pictureBanner.Location = '-1,-1'
			$pictureBanner.Size = '456,50'
			$pictureBanner.Image = $img
			$AltProgressForm.Controls.add($pictureBanner)

			# Add animated spinner
			$spinnerImgPath=$appDeployLogoBanner.Replace("AppDeployToolkitBanner.png","spiffygif_30x30.gif")
            $imgSpinner = [System.Drawing.Image]::Fromfile($spinnerImgPath)
            $pictureBox = New-Object Windows.Forms.PictureBox
            $pictureBox.Location = '15,95'
            $pictureBox.Size = '30,30'
            $pictureBox.Image = $imgSpinner
            $AltProgressForm.controls.add($pictureBox)

			# initializes Label
			$Label = New-Object System.Windows.Forms.Label
			$Label.Name = 'ProgressLabel'
			$Label.Anchor = 'Top,Left'
			$Label.AutoSize = $false
			$Label.Location = '59,52'
			$Label.Size = '350,120'
			$Label.TextAlign = 'MiddleCenter'
			# Font styles are: Regular, Bold, Italic, Underline, Strikeout
			$Font = New-Object System.Drawing.Font("Microsoft Sans Serif",11,[System.Drawing.FontStyle]::Regular)
			$Label.Font = $Font
			$Label.Text = $StatusMessage
			$AltProgressForm.Controls.Add($Label)
			
			#  Create a new runspace for the progress bar
			$global:AltProgressRunspace = [runspacefactory]::CreateRunspace()
			$global:AltProgressRunspace.ApartmentState = 'STA'
			$global:AltProgressRunspace.ThreadOptions = 'ReuseThread'
			$global:AltProgressRunspace.Open()
			
			#  Add other variables from the parent thread required in the progress runspace
			$global:AltProgressRunspace.SessionStateProxy.SetVariable('AltProgressForm', $AltProgressForm)
			
			#  Add the script block to be executed in the progress runspace
			$global:AltProgressCmd = [PowerShell]::Create().AddScript({
     			# show the Form  
     			[System.Windows.Forms.Application]::Run($AltProgressForm)
			})
			
			$AltProgressCmd.Runspace = $global:AltProgressRunspace
			Write-Log -Message "Spin up progress dialog in a separate thread with message: [$statusMessage]." -Source ${CmdletName}
			#  Invoke the progress runspace
			$global:AltProgressHandle=$AltProgressCmd.BeginInvoke()
			#  Allow the thread to be spun up safely before invoking actions against it.
			Start-Sleep -Seconds 1
		}
		## Check if the progress thread is running before invoking methods on it
		Else {
			#  Allow time between updating the thread
			Start-Sleep -Seconds 1
			Write-Log -Message "Update progress message: [$statusMessage]." -Source ${CmdletName}
			$AltProgressForm.Controls['ProgressLabel'].Text = $StatusMessage
		}
	}
	End {
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
	}
}
#endregion


#region Function Close-AltInstallationProgress
Function Close-AltInstallationProgress {
<#
.SYNOPSIS
	Closes the dialog created by Show-AltInstallationProgress.
.DESCRIPTION
	Closes the dialog created by Show-AltInstallationProgress.
	This function is called by the Close-InstallationProgress function to close a running instance of the progress dialog if found.
.EXAMPLE
	Close-AltInstallationProgress
.NOTES
	This is an internal script function and should typically not be called directly.
.LINK
	http://psappdeploytoolkit.codeplex.com
#>
	[CmdletBinding()]
	Param (
	)
	
	Begin {
		## Get the name of this function and write header
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
	}
		
	Process {
		$AltProgressForm.Add_FormClosing({$_.Cancel = $false;}) # re-enable close command to allow form to close.
    	$AltProgressForm.Close() # close form
    	$AltProgressCmd.EndInvoke($AltProgressHandle)
    	$AltProgressRunspace.Close()
    	$AltProgressCmd.Dispose() 
        
        ## Close the progress thread
		Write-Log -Message 'Close the installation progress dialog.' -Source ${CmdletName}
	}
		
	End {
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
	}
}
#endregion
```

**Comment by sintaxasn** [comment] 2015-12-22 22:07
Excellent work!

**Comment by appPackager** [comment] 2016-01-06 21:58
Found a bug in my Close-AltInstallationProgress function when Show-InstallationPrompt is invoked.  Fixed version is as follows:
```
#region Function Close-AltInstallationProgress
Function Close-AltInstallationProgress {
<#
.SYNOPSIS
	Closes the dialog created by Show-AltInstallationProgress.
.DESCRIPTION
	Closes the dialog created by Show-AltInstallationProgress.
	This function is called by the Close-InstallationProgress function to close a running instance of the progress dialog if found.
.EXAMPLE
	Close-AltInstallationProgress
.NOTES
	This is an internal script function and should typically not be called directly.
.LINK
	http://psappdeploytoolkit.codeplex.com
#>
	[CmdletBinding()]
	Param (
	)
	
	Begin {
		## Get the name of this function and write header
		[string]${CmdletName} = $PSCmdlet.MyInvocation.MyCommand.Name
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -CmdletBoundParameters $PSBoundParameters -Header
	}
		
	Process {
		if ($AltProgressForm) {
			$AltProgressForm.Add_FormClosing({$_.Cancel = $false;}) # re-enable close command to allow form to close.
    		$AltProgressForm.Close() # close form
    		$AltProgressCmd.EndInvoke($AltProgressHandle)
    		$AltProgressRunspace.Close()
    		$AltProgressCmd.Dispose() 
        
        	## Close the progress thread
			Write-Log -Message 'Close the installation progress dialog.' -Source ${CmdletName}
		}
	}
		
	End {
		Write-FunctionHeaderOrFooter -CmdletName ${CmdletName} -Footer
	}
}
#endregion
```

**Comment by seanlillis** [comment] 2018-01-16 12:53
This workaround may resolve the issue, is anyone able to integrate this code snippet and test?
https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/disable-the-realtimestylus-for-wpf-applications

**Comment by sintaxasn** [comment] 2018-11-06 20:19
This issue was moved to https://discourse.psappdeploytoolkit.com/t/app-deployment-toolkit-crashes-on-touch-enabled-windows-7-devices/1241

**Comment by mjr4077au** [comment] 2024-10-14 05:39
Closing this one due to its age and the general unsupported nature of Windows 7, along with confirmation the issue does not present itself on newer targets.

**Closed by mjr4077au** 2024-10-14 05:39 UTC
Labels: Status: Help Wanted
