### ISSUE TITLE
2 Apps with same process name

### ISSUE THREAD

**Issue by MechaClick** [PSAppDeployToolkit/PSAppDeployToolkit#431] opened 2019-09-24 13:32 UTC
Hello,

I need to prompt for the closure of an application but my issue is that the process name is the exact same as another application (same app different instance).  The only way to differentiate between the 2 instances is by specifying the path where the .exe was launched.

I'm able to successfully do this with the command below:
get-process | where-object {$_.Path -eq 'c:\app1\app.exe'} | Select-Object path

My question:
is there any way that I can implement this by adjusting a line of code for a 1 off install instance? or is it possible to add this functionality for these circumstances?

Thanks

**Comment by pchatham** [comment] 2019-09-24 13:39
you can already do this, if I am understanding your requirement correctly.

`Show-InstallationWelcome -CloseApps 'App1=NewApp1,lync=Skype for Business'`

Hope this helps

**Comment by MechaClick** [comment] 2019-09-24 14:21
Correct me if i'm wrong here but just reading your If statement, I'm reading it like so:

If (my process is running from specific path) (show-installationwelcome -closeapps 'same situation as before') 

So i don't see how checking if my specific process is running and if it is, prompt to close apps using the same method to close them as before as that "-CloseApps 'App1=NewApp1'" will still equate to BOTH the processes since they are called the same.

In your example if you could check for the specific process running from the specified path and save it to a variable and use that variable to close the specific instance 

$specificApp = get-process | where-object {$_.Path -eq 'c:\App1\App1.exe'} | Select-Object path

Show-InstallationWelcome -CloseApps $specificApp

Hope that makes sense

-CloseApps '$specificApp'

**Comment by luki1412** [comment] 2020-06-22 13:40
You are correct. That wouldn't fix your issue. This needs to be addressed within the code of the function Show-InstallationWelcome

**Comment by PZan** [comment] 2021-02-09 13:58
I'm just curious the hear if there's plans for a fix for this issue? I've attempted to rewrite the function Show-InstallationWelcome, but it turned out to be quite complex, where, in my mind, at least two or three functions would need rewriting in order to work around the problem.

**Comment by luki1412** [comment] 2021-02-09 14:36
I have thought of a way to fix this issue while not breaking compatibility but since we plan to redesign all UI functions in v4, there's no point in adding it now and then reworking the entire function again.

**Comment by mjr4077au** [comment] 2024-10-14 10:27
Duplicate of #81.

**Closed by mjr4077au** 2024-10-14 10:27 UTC
Labels: Status: Duplicate
