### ISSUE TITLE
Deploy-Application.exe Does Not Support Spaces In Parameters

### ISSUE THREAD

**Issue by KingLinkTiger** [PSAppDeployToolkit/PSAppDeployToolkit#335] opened 2018-02-24 21:25 UTC
This issue is somewhat relevant to Issue #200, adding custom parameters to Deploy-Application.ps1. If you add these custom parameters Deploy-Application.exe does not support spaces in them, and if you invoke Deploy-Application.exe with these parameters your script will fail to run. Another thing to now is since the failure occurs before Deploy-Application.ps1 is invoked no logging will occur and the user will not know why their script is failing to run.

---

How to reproduce the issue:

For the following examples I'm running the following command:
```
.\Deploy-Application.exe -FileName "Hello World" -FilePath "C:\Program Files\Hello World"
```

Currently how Deploy-Application.exe handles parameters. This is the output of Deploy-Application.exe that runs Deploy-Application.ps1.
```
C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & 'C:\Users\KLT\Downloads\PSAppDeployToolkit-master\PSAppDeployToolkit-master\Sources\Deploy-Application\Deploy-Application\bin\Debug\Deploy-Application.ps1' -FileName Hello World -FilePath C:\Program Files\Hello World; Exit $LastExitCode }
```

Ideally how Deploy-Application.exe should handle parameters:

```
C:\Windows\System32\WindowsPowerShell\v1.0\PowerShell.exe -ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & 'C:\Users\KLT\Downloads\PSAppDeployToolkit-master\PSAppDeployToolkit-master\Sources\Deploy-Application\Deploy-Application\bin\Debug\Deploy-Application.ps1' -FileName "Hello World" -FilePath "C:\Program Files\Hello World"; Exit $LastExitCode }
```
Notice how currently the quotation marks are removed. I believe the issues to stems from line 26 of [DeployApplication.cs](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/master/Sources/Deploy-Application/Deploy-Application/DeployApplication.cs) where Environment.GetCommandLineArgs() is used. The [.Net documentation](https://msdn.microsoft.com/en-us/library/system.environment.getcommandlineargs(v=vs.110).aspx) shows in its examples that this strips quotation marks when creating the string array.

---

Suggested Fix

I believe an ideal fix would be to use [Environment.CommandLine](https://msdn.microsoft.com/en-us/library/system.environment.commandline(v=vs.110).aspx) instead of  GetCommandLineArgs, which will simply return all of the arguments as a string, which then can be parsed manually within DeployApplication.cs.

I will follow up with a pull request of an example of this fix.

**Comment by sintaxasn** [comment] 2018-11-06 20:13
This issue was moved to https://discourse.psappdeploytoolkit.com/t/deploy-application-exe-does-not-support-spaces-in-parameters/1176

**Comment by esmorun** [comment] 2021-04-15 08:16
This issue is stil causing headaches for me and my colleagues in 2021, space is not the only character that is causing problems. Here is a proposed solution, I can't guarantee that its bullet proof but it solves the space issue.

//Add quotes unless argument in command-line contains dash (Can't remember why I did this to be honest)
>for (int i = 0; i < commandLineArgs.Count; i++)
>{
>string dash = "-";
>if (!commandLineArgs[i].Contains(dash))
>{
>commandLineArgs[i] = '"' + commandLineArgs[i] + '"';
>}
>}

// Define the script block with command line arguments to pass to PowerShell (only slight changes here)
>string scriptblock = null;
>scriptblock = appDeployScriptPath;
>if (commandLineArgs.Count > 0)
>{
>     scriptblock = scriptblock + " " + string.Join(" ", commandLineArgs.ToArray());
>}
>scriptblock = scriptblock + "; Exit $LastExitCode";


// Convert the scriptblock to Base64, this will ensure that it is passed along to powershell as intended. (This is the important part)
>var scriptblockBytes = System.Text.Encoding.Unicode.GetBytes(scriptblock);
>var scriptblockBase64 = Convert.ToBase64String(scriptblockBytes);
>powershellArgs = powershellArgs + " -EncodedCommand " + scriptblockBase64;

Sorry about the formatting, here it is in a complete DeployApplication.cs-file:

[DeployApplication.zip](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/6316137/DeployApplication.zip)

**Comment by mjr4077au** [comment] 2024-12-12 06:00
I'm going to close this one as a "won't fix". The quotes on a command line are meant to encapsulate a value as a whole, they're not meant to form part of the value.

If you need quotes to be preserved when you're passing them through, they should be escaped with a backslash (`\`) just like you would do within cmd.exe or any batch script:

![image](https://github.com/user-attachments/assets/bd051c45-fe3e-4864-8b29-478fc4113a64)
![image](https://github.com/user-attachments/assets/ccf6d687-a85b-470d-8b6f-b6c7ab8e2668)

Any changes here to attempt to make our toolkit easier by removing well known quoting semantics is an overall net-negative for the project. Providing quotes through to `Invoke-AppDeployToolkit.exe` works precisely as I'd expect them too, and for all we know, they work precisely how many others would expect them to work also.

**Closed by mjr4077au** 2024-12-12 06:00 UTC
Labels: Status: Needs Triage
