### ISSUE TITLE
[Bug] Duplicate Assets and String folders (New-ADTTemplate issue?)

### ISSUE THREAD

**Issue by That-Annoying-Guy** [PSAppDeployToolkit/PSAppDeployToolkit#1152] opened 2024-12-10 22:50 UTC
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

According to [4.0.3 docs](https://psappdeploytoolkit.com/docs/deployment-concepts/deployment-structure), there should only be one \Assets\ folder and one \Strings\ folder.

The following is from 4.0.3's [PSAppDeployToolkit_Template_v4.zip](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/releases/download/4.0.3/PSAppDeployToolkit_Template_v4.zip) file

In the Assets folders, the PNGs are binary identical:
\PSAppDeployToolkit_Template_v4\Assets
\PSAppDeployToolkit_Template_v4\PSAppDeployToolkit\Assets

Whereas the Strings folders are interesting. All the  strings.psd files are identical but only the ones in \PSAppDeployToolkit\Strings folders are signed!
\PSAppDeployToolkit_Template_v4\Strings
\PSAppDeployToolkit_Template_v4\PSAppDeployToolkit\Strings

This is either a documentation issue or we have extra files caused by `New-ADTTemplate`

### Steps to reproduce

N/a
This is either a bug or documentation issue

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, fr-CA}
KeyboardLayout       : en-US
TimeZone             : (UTC-05:00) Eastern Time (US & Canada)
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop
```

**Comment by mjr4077au** [comment] 2024-12-10 23:30
Hi @That-Annoying-Guy, this is actually by design. I'll explain.

The module itself is a digitally signed asset, and to ensure the module isn't tampered with, we sign all components of the module, including config.psd1 and all strings.psd1 files. This means that the config and strings within the module can't be modified, and nor should they as you could be using an installed instance of the module inside of Program Files, but you might be a regular user with no permissions to change content in Program Files.

The copy of config and strings along-side the frontend is your copy to modify, with your changes being applied in a layered approach. The import of files is as follows:

* Module loads its default config.psd1 and strings.psd1 file.
* Module loads your local copy, if it exists, and layers it on top.
* Module loads settingsb from the registry, if they exist, and layers them on top.

If you do not customise the config or strings in any way, the folders can be removed and your deployment will work off the module's config/strings directly. We found during private testing, it wasn't obvious to users they could override the module's config until we put copies along-side the frontend.

With this in mind, and as a vetran PSADT user, if you've got suggestions on how we might do this better, we'd definitely be happy to take this onboard.

**Comment by FRacine** [comment] 2024-12-11 12:48
> Hi @That-Annoying-Guy, this is actually by design. I'll explain.
> 
> The module itself is a digitally signed asset, and to ensure the module isn't tampered with, we sign all components of the module, including config.psd1 and all strings.psd1 files. This means that the config and strings within the module can't be modified, and nor should they as you could be using an installed instance of the module inside of Program Files, but you might be a regular user with no permissions to change content in Program Files.
> 
> The copy of config and strings along-side the frontend is your copy to modify, with your changes being applied in a layered approach. The import of files is as follows:
> 
> * Module loads its default config.psd1 and strings.psd1 file.
> * Module loads your local copy, if it exists, and layers it on top.
> * Module loads settingsb from the registry, if they exist, and layers them on top.
> 
> If you do not customise the config or strings in any way, the folders can be removed and your deployment will work off the module's config/strings directly. We found during private testing, it wasn't obvious to users they could override the module's config until we put copies along-side the frontend.
> 
> With this in mind, and as a vetran PSADT user, if you've got suggestions on how we might do this better, we'd definitely be happy to take this onboard.

Is it any documentation explaining what exactly might be change and how? It is unclear. From what you said I understand, the PSADT cannot be modify. This seems to be correct.

In the past, there were errors in the main script and we had to change some lines to make it works. Also the xml was change to be working with our needs.

So what might be editing and how using the edit copy?

**Comment by That-Annoying-Guy** [comment] 2024-12-11 16:58
so this is a documentation issue.

the Deployment Structure - V4 Native Deployment Template page

It should be replaced with something like the following:
```
Invoke-AppDeployToolkit.ps1             # PSADT Deployment PowerShell script
Invoke-AppDeployToolkit.exe             # PSADT Deployment executable (to easily launch the above script)

├───Files                               # Primary installation files
├───SupportFiles                        # Supporting resources or assets
│
├───PSAppDeployToolkit                  # PSADT module files. Please do not modify anything under this folder.
│   │  PSAppDeployToolkit.psd1             # PSADT module manifest. Import this if you want to use the module in your own scripts.
│   │  PSAppDeployToolkit.psm1             # PSADT module script. Contains all the functions and logic.
│   │
│   ├───Assets
│   │   AppIcon.png                     # The icon to display in the PSADT User Interface(Do not edit)
│   │   Banner.Classic.png              # The banner to display in the PSADT Classic User Interface (not used for Fluent dialogs)
│   │
│   ├───bin
│   │   ├───AMD64
│   │   │   └───handle                  #Handle utility needed for ???-ADT??? Function(Do not remove)
│   │   ├───ARM64
│   │   │   └───handle                  #Handle utility (ARM flavor - Do not remove)
│   │   └───i386
│   │       └───handle                  #Handle utility (32bit flavor - Do not remove)
│   │
│   ├───Config
│   │   config.psd1                     # PSADT configuration file - signed copy (Do not edit)
│   │
│   ├───Frontend                        # Extra copy of Front end files? (Do not edit)
│   │   ├───v3
│   │   │   └───AppDeployToolkit
│   │   └───v4
│   │       └───PSAppDeployToolkit.Extensions
│   │
│   ├───lib                             # PSADT Compiled C# functions (Do not attempt to edit)
│   │
│   ├───Strings                         # Signed copy of language strings (Do not edit)
│   │   └───<LanguageCode>
│   │           strings.psd1            # PSADT User Interface language strings for <LanguageCode>.(Do not edit)
│   │       strings.psd1                # PSADT User Interface language strings for English. (Do not edit)
│   │
│   └───Templates
│       New-ADTFunction                 # template for new functions
│
│
├───PSAppDeployToolkit.Extensions       # PSADT Extensions module files. # TODO - write more on this
│   PSAppDeployToolkit.Extensions.psd1
│   PSAppDeployToolkit.Extensions.psm1
│
├───Assets
│   AppIcon.png                         # The icon to display in the PSADT User Interface
│   Banner.Classic.png                  # The banner to display in the PSADT Classic User Interface (not used for Fluent dialogs)
│
├───Config
│   config.psd1                         # PSADT configuration file
│
└───Strings
    └───<LanguageCode>
        strings.psd1                    # PSADT User Interface language strings for <LanguageCode>.
    strings.psd1                        # PSADT User Interface language strings for English.
```

And I have the same concerns as FRacine. 
Does this mean if we need to fix or modify something in PSAppDeployToolkit.psm1, PSADT will detect it and stop the installation?
Or must we have PS Signature policies enabled for this to happen?

PS: I know eventually there will be instructions on how to recompile the PSAppDeployToolkit.psm1/psd1 files.

PS: I would have placed New-ADTFunction.ps1 inside <root>\PSAppDeployToolkit.Extensions\PSAppDeployToolkit.Extensions.psm1

**Comment by mjr4077au** [comment] 2024-12-12 03:59
> Is it any documentation explaining what exactly might be change and how? It is unclear. From what you said I understand, the PSADT cannot be modify. This seems to be correct.
> 
> In the past, there were errors in the main script and we had to change some lines to make it works. Also the xml was change to be working with our needs.
> 
> So what might be editing and how using the edit copy?

You're free to edit the released version of PSAppDeployToolkit, however doing so will break the signature which means it won't import unless you re-sign it or you've got PowerShell's ExecutionPolicy in Bypass or some other permissive mode.


> the Deployment Structure - V4 Native Deployment Template page
> 
> It should be replaced with something like the following:

Thanks for putting this together, I'm sure we can use this to improve our documentation.

> And I have the same concerns as FRacine. Does this mean if we need to fix or modify something in PSAppDeployToolkit.psm1, PSADT will detect it and stop the installation? Or must we have PS Signature policies enabled for this to happen?

What it means is, we've done things so that you can't load in an untampered, signed module, but have the module import tampered config files, which is why we go beyond what PowerShell does here and sign our config/strings.psd1 files, then validate that signature upon import. If you're importing our module in an AllSigned environment, you can be assured that _all_ components of the module are untampered due to our extra validations.

That entire lockdown is bypassed the moment the signature becomes invalid on the module (i.e. by editing the module). Under such a circumstance, you'd need to be bypassing PowerShell's ExecutionPolicy anyway, so at that point we no longer care about the signature on the config/strings.psd1 files.

In saying this, if you're needing to customise the module in a private fork, doing this against the release build with its monolithic 23,000 line .psm1 file would be a bad idea. Our repo should be forked and your changes committed to your fork so that you can easily merge in our changes/fixes/improvements.

> PS: I know eventually there will be instructions on how to recompile the PSAppDeployToolkit.psm1/psd1 files.

I actually thought there already was such information, we'll get that added soon. Building the module is a straight-forward procedure, but you'll need require Visual Studio be installed to do so (not VSCode, proper Visual Studio).

> PS: I would have placed New-ADTFunction.ps1 inside \PSAppDeployToolkit.Extensions\PSAppDeployToolkit.Extensions.psm1

I've done this in a commit that I'll push up shortly.

**Comment by FRacine** [comment] 2024-12-12 11:12
What should be done to adapt the parameters in the config files? We cannot edit and sign by ourself. It is not making sense.
So if there is a bug in the code, that's it nothing can be done until it is fixe by you?

Would you clarify this:
"The copy of config and strings along-side the frontend is your copy to modify, with your changes being applied in a layered approach. The import of files is as follows:

Module loads its default config.psd1 and strings.psd1 file. --> OK
**Module loads your local copy, if it exists, and layers it on top. --> What is this local copy story? How using it?**
Module loads settingsb from the registry, if they exist, and layers them on top."

**Comment by mjr4077au** [comment] 2024-12-12 11:18
![image](https://github.com/user-attachments/assets/0244c4ee-5a45-4ed9-9d3e-7d7e548b11b2)

Red = do not touch
Green = yours to modify

**Comment by FRacine** [comment] 2024-12-12 12:08
> ![image](https://private-user-images.githubusercontent.com/48643140/395132820-0244c4ee-5a45-4ed9-9d3e-7d7e548b11b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMDUyNzMsIm5iZiI6MTczNDAwNDk3MywicGF0aCI6Ii80ODY0MzE0MC8zOTUxMzI4MjAtMDI0NGM0ZWUtNWE0NS00ZWQ5LTlkM2UtN2Q3ZTU0OGIxMWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDEyMDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZGE2YmI1NzAzMmRmZmJmMTMxMmM4YTYzYTMxNDU4MzRiNjVmYjE4YTE1MjQ4YmM2NmY4Mjg4ZjhmZDYyODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xN8bWmwg11BV5JfJoZj-88agNIO2cQaLHi6tLkgn3OI)
> 
> Red = do not touch Green = yours to modify

OK great so its looking first at the root folders and if they are not existing to the main ADT folder. But if we found a bug in the module there is no way to change it and we will have to wait until its fixed? Even for diagnosis purpose it means a pain. No?

**Comment by mjr4077au** [comment] 2024-12-12 12:11
I'll try to be clearer: you can modify the module all you want, but it will break the signed status of it. If this is not important to you (i.e. you do not care about the module being digitally signed/you bypass the execution policy in PowerShell already), go ahead.

**Comment by FRacine** [comment] 2024-12-12 12:31
> I'll try to be clearer: you can modify the module all you want, but it will break the signed status of it. If this is not important to you (i.e. you do not care about the module being digitally signed/you bypass the execution policy in PowerShell already), go ahead.

Hi we are not bypassing. Everything is run Remoted signed. So I am not sure how ADT will react.

**Comment by mjr4077au** [comment] 2024-12-12 12:33
If you're using RemoteSigned, then your ExecutionPolicy for local scripts is effectively already in bypass mode l. If you were using AllSigned, then a modified module would fail to import.

Looking story short, with RemoteSigned there will be no problems if you wish to modify the signed module because you're not enforcing authenticode checks anyway.

**Comment by That-Annoying-Guy** [comment] 2024-12-12 17:26
Hi Mitch, I just want to extend an offer to help you guys with the documentation.
I don't have much in testing capability at the moment but I can offer feedback on the documentation itself.
E.G. You use the term Front Script but never define it. Same thing with term Fluent.
(Don't worry. I understand these terms but I have 30+ years of exp under my belt.)

**Comment by mjr4077au** [comment] 2024-12-12 17:46
@That-Annoying-Guy are you on Discord at all? Maybe @sintaxasn can set up a private chat so we can talk further. My use of the word "frontend" came from referring to the module as the "backend", but I should be saying things like "deployment script" as that vernacular is more known and understood. 

Definitely keen to chat though, and any help would be absolutely appreciated for sure 🤘

**Comment by That-Annoying-Guy** [comment] 2024-12-12 18:36
I am on Discord but Dan is my only contact. He can send you my handle. 

I recommend to continue using Front Script as it infers how it should be used. (Front Script ~ Front Door, Use me. not the Back End)

At my day job, we've been using the Front Script as a term for 10+ years.

**Comment by mjr4077au** [comment] 2024-12-20 22:33
I've been reviewing [the docs](https://psappdeploytoolkit.com/docs/deployment-concepts/deployment-structure#v4-native-deployment-template) and I think the information in there is clear enough. Where it has the comment "PSADT module files. Please do not modify anything under this folder.", this should be interpreted as "you don't need to worry about this folder or anything inside of it".

The documented folder structure is simplified and not 100% fleshed out to not bamboozle users who don't understand things any further than necessary. If you disagree, I'm more than happy to keep talking about it but for now, I'll close this issue.

**Closed by mjr4077au** 2024-12-20 22:33 UTC
Labels: Type: Issue / Bug, Status: Needs Triage
