### ISSUE TITLE
Running on a Domain Controller causes Exception calling “Translate” 

### ISSUE THREAD

**Issue by GbCaa** [PSAppDeployToolkit/PSAppDeployToolkit#618] opened 2021-02-09 03:20 UTC
I had SCCM deploy something to my all servers collection which worked perfectly except on Domain Controllers… No logs were created and no errors in the Event Viewer. Running the EXE manually wouldn’t even open PowerShell. I eventually ran Deploy-Application.ps1 to get this error message:
```
C:\Tmp\Deploy-Application.ps1 : Module [C:\Tmp\AppDeployToolkit\AppDeployToolkitMain.ps1] failed to load:
Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."

At C:\Tmp\Deploy-Application.ps1:98 char:81
+ ... yToolkitMain -DisableLogging } Else { . $moduleAppDeployToolkitMain }
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1
+ .\Deploy-Application.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Deploy-Application.ps1
```
The line 98 that its referring to has to do with “Dot source the required App Deploy Toolkit Functions”… if I try to dot source the AppDeployToolkitMain.ps1 file, it completes but give this error: 
```
Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."
At C:\Tmp\AppDeployToolkit\AppDeployToolkitMain.ps1:270 char:1
+ [string]$LocalPowerUsersGroup = (New-Object -TypeName System.Security ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException
```
If I look at line 270 of AppDeployToolkitMain.ps1, its trying to get the BuiltinPowerUsersSid but this is a Domain Controllers, so groups like Power Users and Administrators are hidden.

**Comment by luki1412** [comment] 2021-02-09 06:12
We are already aware of this issue. It will be fixed in the next release.

Duplicate #612

**Closed** 2021-03-06 14:31 UTC
Labels: bug, duplicate, resolved / implemented

**Comment by mborzik** [comment] 2022-09-29 14:35
Hi,
I have exactly the same issue, using PSADT v3.8.4 on Windows 10 Home Edition. Is there any workaround I could use, or will PSADT simply not work on Win10Home by design (different user account management)?

Thanks.
Martin

**Comment by That-Annoying-Guy** [comment] 2022-09-29 15:01
Well you could download the [4.8.5 beta](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit) that hasn't been given the "released" stamp.  
It hasn't changed in over 16 months and I use it.
Note: No warranties are given for either version.

**Comment by mborzik** [comment] 2022-09-30 16:35
> Well you could download the [4.8.5 beta](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit) that hasn't been given the "released" stamp. It hasn't changed in over 16 months and I use it. Note: No warranties are given for either version.

I have downloaded the beta and it works also on Windows 10 Home. 
Thanks a ton!!
