### ISSUE TITLE
Invoke-HKCURegistrySettingsForAllUsers Not Working

### ISSUE THREAD

**Issue by zeeter82** [PSAppDeployToolkit/PSAppDeployToolkit#862] opened 2024-03-04 17:59 UTC
**My Question/Issue:**
**Invoke-HKCURegistrySettingsForAllUsers** is not working for this specific reg key/location:

`Set-RegistryKey -Key 'HKCU:SOFTWARE\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32' -Name '(Default)' -Value '' -Type String -SID $UserProfile.SID
`

```
My full script block below:
#Set the Registry Settings for all Users 
	
	[scriptblock]$HKCURegistrySettings = 
	{
	Set-RegistryKey -Key 'HKCU:SOFTWARE\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32' -Name '(Default)' -Value '' -Type String -SID $UserProfile.SID
		
	}
	Invoke-HKCURegistrySettingsForAllUsers -RegistrySettings $HKCURegistrySettings
```

**What I have tried so far:**
Googling the issue.  Maybe the \Classes section is special and might not be supported here or I'm doing it the wrong way.

**Copy of log:**
```
<![LOG[[Installation] :: Getting the User Profile Path, User Account SID, and the User Account Name for all users that log onto the machine.]LOG]!><time="12:47:37.619-300" date="03-04-2024" component="Get-UserProfiles" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Converting the SID [S-1-5-18] to an NT Account name.]LOG]!><time="12:47:37.655-300" date="03-04-2024" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Converting the SID [S-1-5-19] to an NT Account name.]LOG]!><time="12:47:37.686-300" date="03-04-2024" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Converting the SID [S-1-5-20] to an NT Account name.]LOG]!><time="12:47:37.720-300" date="03-04-2024" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Converting the SID [S-1-5-21-2052111302-1960408961-839522115-136322] to an NT Account name.]LOG]!><time="12:47:37.735-300" date="03-04-2024" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Converting the SID [S-1-5-21-2052111302-1960408961-839522115-28728] to an NT Account name.]LOG]!><time="12:47:37.750-300" date="03-04-2024" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Converting the SID [S-1-5-21-2052111302-1960408961-839522115-332813] to an NT Account name.]LOG]!><time="12:47:37.781-300" date="03-04-2024" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Loading the User [DOMAIN\user2] registry hive in path [HKEY_USERS\S-1-5-21-2052111302-1960408961-839522115-136322].]LOG]!><time="12:47:37.830-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Executing ScriptBlock to modify HKCU registry settings for all users.]LOG]!><time="12:47:38.051-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Creating registry key [Registry::HKEY_USERS\S-1-5-21-2052111302-1960408961-839522115-136322\SOFTWARE\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32].]LOG]!><time="12:47:38.101-300" date="03-04-2024" component="Set-RegistryKey" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Setting registry key value: [Registry::HKEY_USERS\S-1-5-21-2052111302-1960408961-839522115-136322\SOFTWARE\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32] [(Default) = ].]LOG]!><time="12:47:38.133-300" date="03-04-2024" component="Set-RegistryKey" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Unload the User [DOMAIN\user2] registry hive in path [HKEY_USERS\S-1-5-21-2052111302-1960408961-839522115-136322].]LOG]!><time="12:47:38.163-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: REG.exe failed to unload the registry hive and exited with exit code [1]. Performing manual garbage collection to ensure successful unloading of registry hive.]LOG]!><time="12:47:38.228-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="2" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Unload the User [DOMAIN\user2] registry hive in path [HKEY_USERS\S-1-5-21-2052111302-1960408961-839522115-136322].]LOG]!><time="12:47:43.280-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Loading the User [DOMAIN\user1] registry hive in path [HKEY_USERS\S-1-5-21-2052111302-1960408961-839522115-28728].]LOG]!><time="12:47:43.359-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Executing ScriptBlock to modify HKCU registry settings for all users.]LOG]!><time="12:47:43.453-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Unload the User [DOMAIN\user1] registry hive in path [HKEY_USERS\S-1-5-21-2052111302-1960408961-839522115-28728].]LOG]!><time="12:47:43.515-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: REG.exe failed to unload the registry hive and exited with exit code [1]. Performing manual garbage collection to ensure successful unloading of registry hive.]LOG]!><time="12:47:43.568-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="2" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Unload the User [DOMAIN\user1] registry hive in path [HKEY_USERS\S-1-5-21-2052111302-1960408961-839522115-28728].]LOG]!><time="12:47:48.640-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: The user [DOMAIN\user3] registry hive is already loaded in path [HKEY_USERS\S-1-5-21-2052111302-1960408961-839522115-332813].]LOG]!><time="12:47:48.740-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Executing ScriptBlock to modify HKCU registry settings for all users.]LOG]!><time="12:47:48.751-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Loading the User [Default User] registry hive in path [HKEY_USERS\S-1-5-21-Default-User].]LOG]!><time="12:47:48.798-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Executing ScriptBlock to modify HKCU registry settings for all users.]LOG]!><time="12:47:48.888-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Unload the User [Default User] registry hive in path [HKEY_USERS\S-1-5-21-Default-User].]LOG]!><time="12:47:48.908-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: REG.exe failed to unload the registry hive and exited with exit code [1]. Performing manual garbage collection to ensure successful unloading of registry hive.]LOG]!><time="12:47:48.972-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="2" thread="16856" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Unload the User [Default User] registry hive in path [HKEY_USERS\S-1-5-21-Default-User].]LOG]!><time="12:47:54.005-300" date="03-04-2024" component="Invoke-HKCURegistrySettingsForAllUsers" context="NT AUTHORITY\SYSTEM" type="1" thread="16856" file="Deploy-Application.ps1">
```

Any ideas?

**Comment by That-Annoying-Guy** [comment] 2024-03-04 19:23
what's the error/issue?
The (default) value is not being set?

**Comment by zeeter82** [comment] 2024-03-04 20:30
It seems to set the key/value correctly for existing user profiles, but it's not updating the default so that newly created user profiles get it.

**Comment by That-Annoying-Guy** [comment] 2024-03-11 15:45
I find ActiveSetup more reliable and flexible.
I thought it was not recommended to touch the Default User hive.

**Comment by DanGough** [comment] 2024-04-25 11:51
Closing as unable to reproduce - happy to re-open if we can confirm there is an issue here.

**Closed by DanGough** 2024-04-25 11:51 UTC
