### ISSUE TITLE
Cannot use $appName because space will be removed

### ISSUE THREAD

**Issue by pilgi3** [PSAppDeployToolkit/PSAppDeployToolkit#491] opened 2020-04-30 07:38 UTC
I declare my $appName variable
`[string]$appName = 'VMware Tools'`

Later in the script i want to use the variable like that
`$productCode = Get-CimInstance -ClassName win32_product | where-object {$_.Name -match "$appName"} | Select-Object -ExpandProperty IdentifyingNumber`

But i got an error, because the $appname looks like
`[Pre-Uninstallation] :: VMwareTools`
because the name in the WMI is "VMware Tools".

I think the spaces will be remove because of the logfile name?
Is there a possibility to prevent this?

**Comment by luki1412** [comment] 2020-04-30 14:33
Duplicate of #264

Will look into it.

**Closed** 2020-05-09 08:13 UTC
Labels: duplicate, resolved/implemented
