### ISSUE TITLE
Show-InstallationWelcome doesn't have french support for countdown timer

### ISSUE THREAD

**Issue by JeeBee14** [PSAppDeployToolkit/PSAppDeployToolkit#752] opened 2023-02-07 13:16 UTC
The installation welcome window still shows the countdown in english even though the rest of the UI is in french.
![Screenshot 2023-02-07 081536](https://user-images.githubusercontent.com/80020431/217255016-e2b6b0f7-ecf9-4fca-a2e0-c6240ce9b036.png)

**Comment by That-Annoying-Guy** [comment] 2023-02-07 18:51
I think this is a known issue. The GUI would need an additional variable that would be read from the XML. This new string in the XML would also need to be translated to all currently supported languages. French is not singled out, BTW.

This is one of many GUIs that are using the old way of doing GUIs: WinForms. 
The new way is WPF XAML.

I think the reboot screen has a similar issue.

My impression is that this issue will only be looked at in V4.
Any work in the GUIs should be converting them to WPF XAML and then add the additional variable to resolve your issue.

**Comment by justsomemate** [comment] 2023-03-10 00:41
The XML already has the appropriate strings. It's just not been translated.
![image](https://user-images.githubusercontent.com/80608392/224193390-1228add8-ecef-47d0-b6bc-73e06f27baff.png)

Open AppDeployToolkitConfig.xml in a text editor.
Search for UI_Messages_FR and edit the string in <WelcomePrompt_CountdownMessage></WelcomePrompt_CountdownMessage>

**Comment by That-Annoying-Guy** [comment] 2023-03-10 14:44
IOW: This issue is now fixed in 3.9.2

**Comment by justsomemate** [comment] 2023-03-10 15:29
> IOW: This issue is now fixed in 3.9.2

No, I changed the text in my local copy to have a translated French string. The same (English) string is present in 3.8.4, too

**Comment by That-Annoying-Guy** [comment] 2023-03-10 15:59
**Confirmed!**

        <WelcomePrompt_CountdownMessage>The {0} will automatically continue in:</WelcomePrompt_CountdownMessage>

the string: 

   **The {0} will automatically continue in:**

has not translated for the following languages:
French
Danish
Italian
Japanese
Norwegian (Bokmål)
Polish
Portuguese (Portugal)
Portuguese (Brazil)
Spanish
Swedish
Arabic
Hebrew
Korean
Russian
Chinese (Simplified)
Chinese (Traditional)

**Comment by mmashwani** [comment] 2023-03-12 14:35
If anyone can translate that string to the relevant languages where it's missing, please share them with us and we can add them into the toolkit. We either rely on people to provide us with translations or have a paid service do it for us since we can't be sure if a free online translation service will get it right.

**Comment by JeeBee14** [comment] 2023-03-12 15:04
I could translate it for you guys. The only thing is that in the XML we
would need a conditional value according to the Deployment Type as the
wording would change depending on whether it is "Installation" or
"Désinstallation". Let me know if this is doable in XML and I’ll gladly
translate it for you guys.

**Closed** 2024-04-04 19:29 UTC
Labels: resolved / implemented
