### ISSUE TITLE
Deploy-application.exe -CUSTOMPARAM not working

### ISSUE THREAD

**Issue by PowershellBacon** [PSAppDeployToolkit/PSAppDeployToolkit#649] opened 2021-05-04 18:06 UTC
With this latest version I can no longer pass customer parameters with the exe file. Previous versions I had no issues using customer parameters with the exe file like -region or -deadline. Is this intended or not?

**Comment by That-Annoying-Guy** [comment] 2021-12-03 20:55
Issue confirmed:
https://discourse.psappdeploytoolkit.com/t/will-deploy-application-exe-pass-custom-parameters/3607/11

**Comment by tmeltdowner** [comment] 2022-01-31 17:46
Have the same issue.

**Comment by scotpower** [comment] 2022-11-30 18:37
This problem just popped up for me with version 3.8.4. Running a debug on the Deploy-Application.exe source, <code>List<string> commandLineArgs = new List<string>(Environment.GetCommandLineArgs());</code> strips out double quotes (which I had.)  Single quotes are not removed and using them instead worked.

**Comment by middletonk** [comment] 2023-09-13 21:00
Sorry for the necro post, but I stumbled here via Google. I was able to reproduce this exact same problem on version 3.9.3. However, Scot's comment about using single quotes instead of double continues to work as a workaround! Cheers!

**Comment by mjr4077au** [comment] 2024-10-14 11:13
Duplicate of #200.

**Closed by mjr4077au** 2024-10-14 11:13 UTC
