### ISSUE TITLE
Convert-RegistryPath breaks Set-Registry

### ISSUE THREAD

**Issue by CosmicSingularity** [PSAppDeployToolkit/PSAppDeployToolkit#147] opened 2016-02-18 22:27 UTC
Noticed the following in 3.6.7 and 3.6.8. Had not need to set a key in while.

In the Set-Registry function the line item 3578  $key = Convert-RegistryPath -Key sets the value of $key to:

[02-18-2016 12:22:33.718] [Initialization] [Convert-RegistryPath] :: Return fully qualified registry key path [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Utimaco\SGLOG\Sglog_LogPath]. Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Utimaco\SGLOG\Sglog_LogPath

the the write-log and write-output is returned from the convert-registrypath function and set to $key, which breaks the line item 3585: New-Item -Path $key -ItemType 'Registry' -Force -ErrorAction 'Stop'

```
[02-18-2016 12:22:33.766] [Initialization] [Set-RegistryKey] [Error] :: Failed to set registry key [[02-18-2016 12:22:33.718] [Initialization] [Convert-RegistryPath] :: Return fully qualified registry key path [Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Utimaco\SGLOG\Sglog_LogPath]. Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Utimaco\SGLOG\Sglog_LogPath]. 
```

**Comment by amotaz** [comment] 2016-02-19 14:39
This is an Odd error, I'm not able to find how this is possible in the code. I'm also not able to reproduce as the function works fine for me. Can you please provide a copy of the code you're using to call the function.

**Comment by CosmicSingularity** [comment] 2016-02-19 15:59
In PowerGui, I Debug (Run) appdeploytoolkmain.ps1 so it is dot sourced and the functions are in memory.  From the command line I call set-registry function.

**Comment by mmashwani** [comment] 2016-02-19 17:32
Please provide more details. Like the code you are executing and the full log file. Also, sometimes strange issues crop up if not using the PowerShell console host. Even the PowerShell ISE can cause weird issues sometimes. Please execute in the PowerShell console host and then share details and log results.

**Comment by mmashwani** [comment] 2016-03-14 21:15
@CosmicSingularity Please provide the above requested details to help resolve this issue or close it out if it is not an issue anymore.

**Comment by amotaz** [comment] 2016-12-16 22:00
Hi CosmicSingularity, any updates on this?

**Comment by luki1412** [comment] 2020-07-30 10:02
Cannot be replicated and this is a 4y old issue without enough evidence.

**Closed by luki1412** 2020-07-30 10:02 UTC
