### ISSUE TITLE
[Bug] Show-InstallationPrompt via MCM/SCCM is not displayed for interactive installations

### ISSUE THREAD

**Issue by GeoSimos** [PSAppDeployToolkit/PSAppDeployToolkit#1004] opened 2024-06-14 16:09 UTC
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

Hello,
I have an installation based on v.3.8.4 and it was working as expected when using the Show-InstallationPrompt function, the windows got minimized and the message I wanted was displayed to the currently logged on user when deployed via MCM/SCCM. However in the latest toolkit, this works when testing locally as an admin account and system account (using psexec), but it doesn't for MCM.
The settings are the following:
In the Deploy-Application.ps1 script: **Show-InstallationPrompt -Title "Installation of $($appName), v.$($appVersion)" -MessageAlignment Center -Message "Your device will be restarted upon completion. In case you are teleworking, please be advised that this operation will disconnect you from VPN immediately." -ButtonMiddleText "OK" -Icon Information -MinimizeWindows $true**
**I'm using Execute-Process for the setup executable to install.**

The deployment settings are:

- Program: _PowerShell.exe -ExecutionPolicy Bypass -Command ".\Deploy-Application.ps1 -DeploymentType Install -DeployMode Interactive"_
**User Experience**:
- Installation behavior: _Installation for System_
- Logon requirement: _Whether or not a user is logged on /  Only when a user is logged on (both were working fine before)_
- Visibility: _Hidden (Tried also minimized, normal, all the same outcome)._
- Checked option of "Allow the users to view and interact with the program installation"
 
In the log file the displaying of the installation prompt is reported, the windows get minimized but the installation prompt is not displayed. I tested it with console and RDP sessions, the behavior is the same.
To stop it I have to terminate the PowerShell process that runs the deployment.
Could you please check it?

### Steps to reproduce

1. As described above
2.
3.

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, el-GR}
KeyboardLayout       : en-US
TimeZone             : (UTC+02:00) Athens, Bucharest
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile


Host:
  Version:      7.0.20
  Architecture: x64
  Commit:       0fb6ac59fb

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by apiontek** [comment] 2024-06-14 19:41
I am also seeing this issue. PSADT v3.9.3, Interactive SCCM install, no deferral, Show-InstallationWelcome comes up visible. But v3.10.1, the log indicates it has been displayed, but nothing comes up on screen.

However, if I locally use PSExec to get a SYSTEM shell, and then run the same code, the Welcome prompt comes up visible. It's only when SCCM is running it. The SCCM program has definitely been configured to allow the user to interact, and the same config is working with v3.9.3.

What's more, if I set AllowDefer, then the welcome prompt shows up. It's only failing to show up if AllowDefer is disabled.

**Comment by FRacine** [comment] 2024-06-14 21:54
I believe it is not sccm but the way it is launch. With SCCM it is not interactive and running in session 0. So I would believe, it is using the task scheduler to launch it on the logged on user. I have a similair issue with activesetup launch with SCCM.

**Comment by apiontek** [comment] 2024-06-15 14:15
I can't speak for OP, but the issue I am describing is specifically SCCM running powershell -File install-script.ps1, there's no scheduled task involved. And as reported, the checkbox in SCCM to allow interactivity is checked, so it has access to a user session. The dialog does display if I allowed deferrall, or if I use an older version of PSADT. So the issue seems different from what you are referencing.

**Comment by GeoSimos** [comment] 2024-06-15 18:35
> I am also seeing this issue. PSADT v3.9.3, Interactive SCCM install, no deferral, Show-InstallationWelcome comes up visible. But v3.10.1, the log indicates it has been displayed, but nothing comes up on screen.
> 
> However, if I locally use PSExec to get a SYSTEM shell, and then run the same code, the Welcome prompt comes up visible. It's only when SCCM is running it. The SCCM program has definitely been configured to allow the user to interact, and the same config is working with v3.9.3.
> 
> What's more, if I set AllowDefer, then the welcome prompt shows up. It's only failing to show up if AllowDefer is disabled.

This pops another question though, hasn't the developers team tested those scenarios before releasing it? If the functionality is broken for MCM/SCCM since toolkit v3.9.3 then we have a bigger problem.....

**Comment by GeoSimos** [comment] 2024-06-15 18:37
> I believe it is not sccm but the way it is launch. With SCCM it is not interactive and running in session 0. So I would believe, it is using the task scheduler to launch it on the logged on user. I have a similair issue with activesetup launch with SCCM.

Thanks for the pointing to the task scheduler tasks, I will check what is created during the deployment and will compare it with v.3.8.4.
From my experience, v3.8.4 is quite stable for my requirements and even the activesetup worked fine for a complex deployment I done 2 months ago.

**Comment by GeoSimos** [comment] 2024-06-15 18:40
> I can't speak for OP, but the issue I am describing is specifically SCCM running powershell -File install-script.ps1, there's no scheduled task involved. And as reported, the checkbox in SCCM to allow interactivity is checked, so it has access to a user session. The dialog does display if I allowed deferrall, or if I use an older version of PSADT. So the issue seems different from what you are referencing.

Definitely something is wrong here, I would love to do code comparisons to find out the issue, but at present time I don't have the time to do so due to pressing tasks to deliver.

**Comment by FRacine** [comment] 2024-06-16 10:33
> I can't speak for OP, but the issue I am describing is specifically SCCM running powershell -File install-script.ps1, there's no scheduled task involved. And as reported, the checkbox in SCCM to allow interactivity is checked, so it has access to a user session. The dialog does display if I allowed deferrall, or if I use an older version of PSADT. So the issue seems different from what you are referencing.

Hi,

I am developping since a lot of time with PSADTK. With respect, I would assure you, you don,t need checking user interactivity. The only time, you would need it is for some software install like some oracle product. PSADTK, is using execute process as user to breach session 0. If there is a session 0, it create a task scheduler to run window or activesetup.

**Comment by apiontek** [comment] 2024-06-17 20:46
If one uses `Execute-ProcessAsUser` then PSADT will use Task Scheduler to run a script as the user. And the functions `Show-BalloonTip` and `Set-ActiveSetup` do indeed make use of that function. However, with respect, I assure you, nowhere in the function `Show-WelcomePrompt` nor anywhere else in `AppDeployToolkitMain.ps1` is this approach used.

This issue is most likely due to changes `Show-WelcomePrompt` I suspect. If I get some time I'll try to figure out what changes cause the issue.

**Comment by FRacine** [comment] 2024-06-17 21:38
> If one uses `Execute-ProcessAsUser` then PSADT will use Task Scheduler to run a script as the user. And the functions `Show-BalloonTip` and `Set-ActiveSetup` do indeed make use of that function. However, with respect, I assure you, nowhere in the function `Show-WelcomePrompt` nor anywhere else in `AppDeployToolkitMain.ps1` is this approach used.
> 
> This issue is most likely due to changes `Show-WelcomePrompt` I suspect. If I get some time I'll try to figure out what changes cause the issue.

Then how anything would show up to a user through session 0?

**Comment by DanGough** [comment] 2024-06-18 06:24
PSADT does not have native capability to make the UI visible from session 0. With ConfigMgr you have to select the option to allow the user to interact, and with Intune you need to use ServiceUI.exe to make the toolkit visible.

I'll see if I can reproduce these issues this week.

**Comment by GeoSimos** [comment] 2024-06-18 10:00
> PSADT does not have native capability to make the UI visible from session 0. With ConfigMgr you have to select the option to allow the user to interact, and with Intune you need to use ServiceUI.exe to make the toolkit visible.
> 
> I'll see if I can reproduce these issues this week.

Indeed, but if you check my updates to the issue above and the comments you will realize that this is a bug :-)

**Comment by GeoSimos** [comment] 2024-06-18 10:09
I did some extra tests on version 3.10.1 and they are not good, for an interactive deployment via SCCM we have:
1) When visibility is set as hidden, it is logged as displayed but never shown
2) If you set the  Logon requirement to "whether a user is logged on or not", when no user is logged on, PSADT switches automatically to silent (I guess that is ok).
3) When visibility is set as minimized, a powershell window is displayed on the taskbar for the script and another one for the "Show-InstallationPrompt" but the latter is not topmost (the windows get minimized), unless the user clicks on the taskbar icon.
I didn't tested for visibility Normal and Maximized because of time constraints, I may do so at another time but they are not relevant to the usage scenario.
@seanlillis , @sintaxasn please take a look at this issue, it seems to be broken.....

**Comment by DanGough** [comment] 2024-06-18 10:28
Some of those tests have expected outcomes.

1. Setting as hidden in SCCM have no effect on the visibility of PSADT dialogs other than perhaps hiding the console window if your command line is pointing to powershell.exe. If you want the UI to be visible without a console window showing to the user, you should be using Deploy-Application.exe. You will need to tick the option to allow users to interact with the installation however.

2. This is expected and by design.

3. Again, rather than messing with minimised/hidden options in SCCM, try just using Deploy-Application.exe. It's entire purpose is to run hidden and then it launches Powershell, also hidden.

I'm not saying there are no bugs here, this is still to be investigated from our side.

**Comment by DanGough** [comment] 2024-06-18 12:14
I am Dan Gough - but I am working with Dan C (sintaxasn) on the project.

**Comment by apiontek** [comment] 2024-06-18 13:55
We had issues in the past not getting proper exit codes from using the EXE so we use the PowerShell directly. I would be surprised if using the EXE helped here, given the behavior I'm seeing.

We have a number of customizations so I decided to re-test with stock PSADT downloaded from the Releases page here.

- v3.9.3, SCCM Package/Program configured Hidden, run with Admin rights, when User logged in, Allow user to interact, same command we always use, basically `"%Windir%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -File Deploy-Application.ps1`
  - Within script, with Outlook, Word, Excel running, `Show-InstallationWelcome -CloseApps 'outlook,winword,excel' -AllowDefer -DeferTimes 999 -CheckDiskSpace -PersistPrompt -MinimizeWindows $False -BlockExecution -PromptToSave`:
    - working, dialog displays prompting to close applications
  - And, same situation, `Show-InstallationWelcome -CloseApps 'outlook,winword,excel' -CheckDiskSpace -PersistPrompt -MinimizeWindows $False -BlockExecution -PromptToSave`:
    - working, dialog displays prompting to close applications
- v3.10.0, exact same SCCM Package/Program configuration & command line:
  - With Outlook, Word, Excel running, `Show-InstallationWelcome -CloseApps 'outlook,winword,excel' -AllowDefer -DeferTimes 999 -CheckDiskSpace -PersistPrompt -MinimizeWindows $False -BlockExecution -PromptToSave`:
    - working, dialog displays prompting to close applications
  - And, same situation, `Show-InstallationWelcome -CloseApps 'outlook,winword,excel' -CheckDiskSpace -PersistPrompt -MinimizeWindows $False -BlockExecution -PromptToSave`:
    - **This is the failing condition:** no dialog displays, but log indicates `Show-WelcomePrompt` has parsed the apps that need closing

```
[Pre-Installation] :: Prompting the user to close application(s) [Microsoft Excel,Microsoft Outlook,Microsoft Word]...	Show-WelcomePrompt	6/18/2024 9:33:12 AM	71716 (0x11824)
[Pre-Installation] :: The running processes have changed. Updating the apps to close: [Microsoft Excel,Microsoft Outlook,Microsoft Word]...	Show-WelcomePrompt	6/18/2024 9:33:15 AM	71716 (0x11824)
```

Seems like something specifically between v3.9.3 & 3.10.0 with Show-WelcomePrompt when not handling deferral, but only when running via SCCM. Strange that the dialog does display if I run the same command line from a SYSTEM shell.

**Comment by GeoSimos** [comment] 2024-06-18 15:16
> * v3.9.3, SCCM Package/Program configured Hidden, run with Admin rights, when User logged in, Allow user to interact, same command we always use, basically `"%Windir%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -File Deploy-Application.ps1`
 A bit irrelevant but do you need to run it as such, I mean from the sysnative path. SCCM can handle this quite well if you check the box to run this program as 32-bit. The logs show that the 32-bit PowerShell interpreter ran.

**Comment by DanGough** [comment] 2024-06-18 18:56
There is a known issue with 3.10.0 for this - please use 3.10.1 if doing any testing for this issue.

**Comment by apiontek** [comment] 2024-06-18 19:01
@GeoSimos In fact, both SCCM and Intune will run installers in a 32-bit environment by default. The use of the `sysnative` path is to force the execution into a 64-bit environment. I did not post the full log so I'm not sure what you're referring to, but the same log file I pulled the other two lines from indicates:

```
[Initialization] :: PowerShell Version is [5.1.19041.4522 x64]	PSAppDeployToolkit	6/18/2024 9:52:32 AM	67364 (0x10724)
```

**Comment by apiontek** [comment] 2024-06-18 19:20
The log where I'm reproducing the issue shows it ran Interactive, even in 3.10.0, so that's not the problem. I appreciate the thoughts about using the exe but right now I'm not interested in also revisiting how we launch the toolkit and whether there's still an issue with exit codes (could have been something I was doing wrong when we first adopted the toolkit 3-4 years ago). The approach we're using has been working fine for us. You know, if it isn't broken, don't fix it!

The only issue at hand for me here is this one specific circumstance where the welcome prompt window isn't appearing. I'll do some more testing, turn on debug, see if I can revert individual changes to get the prompt to appear, and report back if I find anything useful.

**Comment by apiontek** [comment] 2024-06-18 23:58
I believe I have found a fix, and it is reverting one line of code in `Show-WelcomePrompt`.

What's more, I was able to reproduce @GeoSimos issue with `Show-InstallationPrompt` — and it has a similar fix.

### Show-WelcomePrompt

From v3.9.3, [AppDeployToolkitMain.ps1 line 9474](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/2ba55ab200bd3826c989fb725d899e48f2ee36fd/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L9474):

```powershell
$formWelcome.WindowState = 'Normal'
```

If I paste that back in to v3.10.1 at basically the same place, [just after line 10139](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/eddfcb6e6bf1d28b539b0d407818e04a6d2a1347/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L10139), then `Show-WelcomePrompt` starts working as expected.

I can't tell why, when deferral is enabled, the prompt displays, but when deferral is not enabled, without the above line restored, the prompt does not appear, and with the line, it does appear.

### Show-InstallationPrompt

From v3.9.3, [AppDeployToolkitMain.ps1 line 2252](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/2ba55ab200bd3826c989fb725d899e48f2ee36fd/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L2252):

```powershell
$formInstallationPrompt.WindowState = 'Normal'
```

If I paste that back in to v3.10.1 at basically the same place, [just after line 2367](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/blob/eddfcb6e6bf1d28b539b0d407818e04a6d2a1347/Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1#L2367), then `Show-InstallationPrompt` starts working as expected.

Can anyone else reproduce and confirm? I'm happy to do a pull request if needed. It would be good to get these dialogs working in these circumstances again, especially if that's all that's needed.

**Comment by mjr4077au** [comment] 2024-06-19 03:16
My turn to reply now, and acknowledge that if the above is indeed the fix, then its an issue I caused while making the code HiDPI compatible. I believe my thought process at the time was that the window's default state is `Normal`, so the line wasn't required, but I neglected to see that other parts of the code are minimising the window upon certain actions.

I've patched this in our v4 development branch and will discuss the possibility of a 3.10.2 release as there's a few other little things that I believe we wish to fix to give the 3.x codebase its final swansong.

**Comment by CoyoteProd** [comment] 2024-06-19 10:51
Just for information (and after days of trying) : 
If they are single quote in -message and -nowait parameter, then dialog wont display.

**Comment by FRacine** [comment] 2024-06-19 11:41
> > I believe it is not sccm but the way it is launch. With SCCM it is not interactive and running in session 0. So I would believe, it is using the task scheduler to launch it on the logged on user. I have a similair issue with activesetup launch with SCCM.
> 
> Thanks for the pointing to the task scheduler tasks, I will check what is created during the deployment and will compare it with v.3.8.4. From my experience, v3.8.4 is quite stable for my requirements and even the activesetup worked fine for a complex deployment I done 2 months ago.

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/999

**Comment by GeoSimos** [comment] 2024-06-19 14:16
> @GeoSimos In fact, both SCCM and Intune will run installers in a 32-bit environment by default. The use of the `sysnative` path is to force the execution into a 64-bit environment. I did not post the full log so I'm not sure what you're referring to, but the same log file I pulled the other two lines from indicates `x64`:
> 
> ```
> [Initialization] :: PowerShell Version is [5.1.19041.4522 x64]	PSAppDeployToolkit	6/18/2024 9:52:32 AM	67364 (0x10724)
> ```

Unless I'm missing something, the PowerShell.exe under C:\Windows\System32\WindowsPowerShell\v1.0\ is actually the x64 one.
There was only one case I had to call PowerShell via the SysNative path but it was because an x86 process had to access x64 executables of the OS. Maybe this will clarify a bit when to use it https://www.samlogic.net/articles/sysnative-folder-64-bit-windows.htm.

**Comment by GeoSimos** [comment] 2024-06-19 14:52
> The known issue introduced in 3.10.0 (and fixed in 3.10.1) made the toolkit incorrectly detect OOBE and switch to silent installation when an interactive installation was chosen.
> 
> I thought SCCM runs in 64-bit mode by default these days using the Application model, as there’s a radio button to change it to 32-bit, which is not the default option... Installing a Package rather than an Application may be different though. That’s another reason to use Deploy-Application.exe as it will ensure the 64-bit PowerShell host is used on a 64-bit OS!
> 
> If error codes are not being returned properly when using the exe, then this is a new one to me that can be logged as a separate issue (we already have 2 different issues being discussed in this one!).

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1004#issuecomment-2178831490

**Comment by GeoSimos** [comment] 2024-06-19 14:55
> My turn to reply now, and acknowledge that if the above is indeed the fix, then its an issue I caused while making the code HiDPI compatible. I believe my thought process at the time was that the window's default state is `Normal`, so the line wasn't required, but I neglected to see that other parts of the code are minimising the window upon certain actions.
> 
> I've patched this in our v4 development branch and will discuss the possibility of a 3.10.2 release as there's a few other little things that I believe we wish to fix to give the 3.x codebase its final swansong.

We're coming after you Mitch :)

**Comment by GeoSimos** [comment] 2024-06-19 14:57
> Just for information (and after days of trying) : If they are single quote in -message (for exemple in french) and have -nowait parameter, then dialog won't display.

I think you have to escape them properly to work, had pulled my hair sometimes but it's how PowerShell handles special characters in quoted blocks.

**Comment by mjr4077au** [comment] 2024-06-19 22:30
> > My turn to reply now, and acknowledge that if the above is indeed the fix, then its an issue I caused while making the code HiDPI compatible. I believe my thought process at the time was that the window's default state is `Normal`, so the line wasn't required, but I neglected to see that other parts of the code are minimising the window upon certain actions.
> > I've patched this in our v4 development branch and will discuss the possibility of a 3.10.2 release as there's a few other little things that I believe we wish to fix to give the 3.x codebase its final swansong.
> 
> We're coming after you Mitch :)

![image](https://media1.tenor.com/m/pXe-GokoyA0AAAAC/the-s-impsons-bush.gif)


> > @GeoSimos In fact, both SCCM and Intune will run installers in a 32-bit environment by default. The use of the `sysnative` path is to force the execution into a 64-bit environment. I did not post the full log so I'm not sure what you're referring to, but the same log file I pulled the other two lines from indicates `x64`:
> > ```
> > [Initialization] :: PowerShell Version is [5.1.19041.4522 x64]	PSAppDeployToolkit	6/18/2024 9:52:32 AM	67364 (0x10724)
> > ```
> 
> Unless I'm missing something, the PowerShell.exe under C:\Windows\System32\WindowsPowerShell\v1.0\ is actually the x64 one. There was only one case I had to call PowerShell via the SysNative path but it was because an x86 process had to access x64 executables of the OS. Maybe this will clarify a bit when to use it https://www.samlogic.net/articles/sysnative-folder-64-bit-windows.htm. From a PSADT based deployment that is x64 via SCCM, here is my initialization statement without any sysnative path, just _PowerShell.exe -ExecutionPolicy Bypass -Command ".\Deploy-Application.ps1 -DeploymentType Install -DeployMode Interactive -Verbose"_
> 
> > ```
> > [Initialization] :: PowerShell Version is [5.1.19041.4412 x64]
> > ```

The sysnative stuff is mostly important for Intune deployments, where the Intune Management Extension (IME/sidecar) is a 32-bit app.


> > Just for information (and after days of trying) : If they are single quote in -message (for exemple in french) and have -nowait parameter, then dialog won't display.
> 
> I think you have to escape them properly to work, had pulled my hair sometimes but it's how PowerShell handles special characters in quoted blocks.

The way we're processing asynchronous operations in the project has changed, the caller shouldn't have to understand quoting symantics to simply display a message.

**Comment by GeoSimos** [comment] 2024-06-20 21:06
> ![image](https://camo.githubusercontent.com/5fa60df02b0a673ce243b09dd1b52cf6f871b5781fdd66a4ec61350cc126964a/68747470733a2f2f6d65646961312e74656e6f722e636f6d2f6d2f7058652d476f6b6f79413041414141432f7468652d732d696d70736f6e732d627573682e676966) 
> 
ROFL!

> The sysnative stuff is mostly important for Intune deployments, where the Intune Management Extension (IME/sidecar) is a 32-bit app.
>
That's what I was aware of the intune app deployment.
 
> > > Just for information (and after days of trying) : If they are single quote in -message (for exemple in french) and have -nowait parameter, then dialog won't display.
> > 
> > 
> > I think you have to escape them properly to work, had pulled my hair sometimes but it's how PowerShell handles special characters in quoted blocks.
> 
> The way we're processing asynchronous operations in the project has changed, the caller shouldn't have to understand quoting symantics to simply display a message.

Thanks for the clarification Mitch, can you provide examples please?
Does this applies to parameter blocks also in functions like Execute-Process?

**Comment by sintaxasn** [comment] 2024-06-20 21:15
We’ll be discussing in more detail at a further date when things are a little more finalized. But it’s worth noting that we will be supporting the existing v3 script type and all existing functions will continue to work - due to some exceptional wizardry being pulled off :)

**Comment by apiontek** [comment] 2024-06-21 16:11
Understand if it's not yet certain, but is there likely to be another v3 release with any additional fixes such as this, or should those of us affected by this just patch our local repos and deployments? I guess I'm going to do that anyway for now, just curious.

**Comment by sintaxasn** [comment] 2024-06-21 19:30
Realistically, we will have a 3.10.2 release that targets a small number of community-identified bugs. Our focus right now is travel - we're getting most of the PSADT dev team together in Belgium for PSConfEU next week, where we'll be giving a technical deep dive on the V4 architecture. We're very proud of what's been done so far. When we get back, I think it makes sense to pivot briefly, and tackle this bugfix release.

However, we have ambitious goals and timelines for V4. We do really need to pull back on V3 so, beyond a couple of identified bugs we want to target, there'll be no room for new features.

**Comment by FRacine** [comment] 2024-06-21 20:14
> Realistically, we will have a 3.10.2 release that targets a small number of community-identified bugs. Our focus right now is travel - we're getting most of the PSADT dev team together in Belgium for PSConfEU next week, where we'll be giving a technical deep dive on the V4 architecture. We're very proud of what's been done so far. When we get back, I think it makes sense to pivot briefly, and tackle this bugfix release.
> 
> However, we have ambitious goals and timelines for V4. We do really need to pull back on V3 so, beyond a couple of identified bugs we want to target, there'll be no room for new features.

With V4, should we worry about all of our scripts?

**Comment by sintaxasn** [comment] 2024-06-21 20:41
You do not need to worry about your V3 scripts 😁

**Comment by ClientMGMT** [comment] 2024-06-26 13:49
> Realistically, we will have a 3.10.2 release that targets a small number of community-identified bugs. Our focus right now is travel - we're getting most of the PSADT dev team together in Belgium for PSConfEU next week, where we'll be giving a technical deep dive on the V4 architecture. We're very proud of what's been done so far. When we get back, I think it makes sense to pivot briefly, and tackle this bugfix release.
> 
> However, we have ambitious goals and timelines for V4. We do really need to pull back on V3 so, beyond a couple of identified bugs we want to target, there'll be no room for new features.

Will the technical deep dive on the V4 architecture session be recorded and put online? A lot of people would probably want to see that session.

**Closed** 2024-08-13 19:08 UTC
Labels: Type: Issue / Bug, Status: Complete
