### ISSUE TITLE
LocalPowerUserGroup variable in AppDeployToolkitMain causes problems on DCs

### ISSUE THREAD

**Issue by peterlustig187** [PSAppDeployToolkit/PSAppDeployToolkit#834] opened 2023-09-14 08:15 UTC
**Describe the bug**
While trying to install software on DCs the following line causes an error and breaks the installation process.

`[string]$LocalPowerUsersGroup = (New-Object -TypeName System.Security.Principal.SecurityIdentifier -ArgumentList ([Security.Principal.WellKnownSidType]::'BuiltinPowerUsersSid', $null)).Translate([System.Security.Principal.NTAccount]).Value`

The powerusergroup does not exist on DCs and therefore can not be read.
If i delete the line the installation process runs without any problems.

**To Reproduce**
Use the AppdeployToolkitMain.ps1 for package installation on DC

**Toolkit Version:**
3.8.4

**Powershell Version:**
5.1.14393.5582

**Comment by seanlillis** [comment] 2024-03-03 17:21
This is a duplicate of #634, which was fixed in 3.9.0. Please download the latest release.

**Closed by seanlillis** 2024-03-03 17:21 UTC
