### ISSUE TITLE
[Bug] Button on Close Apps dialog does not reflect deployment type

### ISSUE THREAD

**Issue by DanGough** [PSAppDeployToolkit/PSAppDeployToolkit#1140] opened 2024-12-09 17:46 UTC
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

The button here should either change Install to Uninstall/Repair as appropriate (preferred), or simply replace it with a generic 'Close Apps & Continue'.

![image](https://github.com/user-attachments/assets/6bd96c2e-1c7e-43fe-b7ad-ae48b9f5eaa3)

### Steps to reproduce

1. Use one of the example app deployment scripts and uninstall with the application running

### Environment data

```console
😁
```

**Comment by mjr4077au** [comment] 2024-12-12 05:49
Duplicate of https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/41, let's track this there.

**Closed by mjr4077au** 2024-12-12 05:49 UTC
Labels: Type: Issue / Bug
