### ISSUE TITLE
Robocopy error code 16 

### ISSUE THREAD

**Issue by equillibrium** [PSAppDeployToolkit/PSAppDeployToolkit#868] opened 2024-03-10 10:48 UTC
**Describe the bug**
My code:
        $ScriptStartTime = Get-Date
        $LogsFileShareFolder = "\\MYSERVER\logs\PSADT\MYCLIENTNAME\"
        # Usual PSADT Install Script here, and then at the end of the file:
	$CopyLogs = (Get-ChildItem $configToolkitLogDir | Where-Object LastWriteTime -ge $ScriptStartTime).FullName
        if ($CopyLogs) {
            $CopyLogs | ForEach-Object {Copy-File -Path $_ -Destination $LogsFileShareFolder -Recurse -Verbose}
        }
Always gets error code 16:

[03-10-2024 13:07:24.354] [Post-Installation] [Execute-Process] :: Executing [C:\WINDOWS\System32\Robocopy.exe /IM /E "C:\ProgramData\Logs\Software\MYAPP.log" "\\MYSERVER\logs\PSADT\MYCLIENTNAME\" /LOG:"C:\ProgramData\Logs\Software\MYAPP_Robocopy.log"]...
[03-10-2024 13:07:24.432] [Post-Installation] [Execute-Process] :: PassThru parameter specified, returning execution results object.
[03-10-2024 13:07:24.440] [Post-Installation] [Execute-Process] :: Execution failed with exit code [16].

**To Reproduce**
Try to use Copy-File with parametrs like before implementing Robocopy. It works with config.xml Use Robocopy set to false.

**Screenshots**
Pasted output above

**Toolkit Version:**
3.9.4

**Powershell Version:**
5.1

**Additional context**

**Comment by That-Annoying-Guy** [comment] 2024-03-10 17:00
Errorcode 16 means syntax or a permissions issue.
 https://ss64.com/nt/robocopy-exit.html

Try the robocopy line outside of PSADT.

**Comment by That-Annoying-Guy** [comment] 2024-03-13 02:27
Looks like they are are going to fix this in 3.9.4.

**Comment by seanlillis** [comment] 2024-03-14 17:25
@equillibrium we've added handling for error 16 and we've tested copying to network shares but couldn't reproduce your issue. Per @That-Annoying-Guy's suggestion, try running the command with robocopy outside PSADT and let us know the result.

**Comment by DanGough** [comment] 2024-03-15 14:47
Clue is in the log - it appears that you are copying to \MYSERVER instead of \\MYSERVER?

I'll assume that was the cause and close this for now, it can be re-opened if there is indeed a problem with the new Robocopy implementation. I will be testing it today also to see if I can break it!

**Comment by DanGough** [comment] 2024-03-15 14:49
... and upon closing I found that Github is converting double backslashes to single ones unless you put it in a codeblock.

So this could still be valid after all, I will try to repro. Please could you confirm @equillibrium!

**Comment by DanGough** [comment] 2024-03-18 13:21
I am also getting error 16 on just a regular simple file copy to a local folder.

**Comment by DanGough** [comment] 2024-03-18 14:05
Could not reproduce using the same code posted.

Also, further info - it currently only uses robocopy if given a folder to copy rather than a file; and error code 16 is generated when asking it to copy something that does not exist.

**Comment by equillibrium** [comment] 2024-03-30 14:20
The issue is resolved in 3.10, thank you

**Comment by DanGough** [comment] 2024-05-09 16:32
Thanks, I will investigate and report back.

**Comment by snowmountainer** [comment] 2024-05-18 14:09
The error situation occurs with version 3.10.1. Version 3.10.0 works.

**Comment by ElianeMegert** [comment] 2024-05-21 09:25
Also having troubles using "old lines" (not robocopy) to copy a folder e.g
Copy-File -Path "$dirSupportFiles\Userconfig" -Destination "$envAppData\" -Recurse
this will endup in error 16. when I toggle off the use of robocopy the command works fine and copies the folder. Is it meant to cover the same syntax? if yes then  someone might look into this

**Comment by ElianeMegert** [comment] 2024-05-21 09:56
> Also having troubles using "old lines" (not robocopy) to copy a folder e.g Copy-File -Path "$dirSupportFiles\Userconfig" -Destination "$envAppData" -Recurse this will endup in error 16. when I toggle off the use of robocopy the command works fine and copies the folder. Is it meant to cover the same syntax? if yes then someone might look into this

use '-UseRobocopy $false' on such commands helps. not that big of a deal

**Comment by DanGough** [comment] 2024-05-21 10:00
> Also having troubles using "old lines" (not robocopy) to copy a folder e.g Copy-File -Path "$dirSupportFiles\Userconfig" -Destination "$envAppData" -Recurse this will endup in error 16. when I toggle off the use of robocopy the command works fine and copies the folder. Is it meant to cover the same syntax? if yes then someone might look into this

That particular syntax is working fine for me, could you post the output of the log file please and confirm you're using 3.10.1?

**Comment by ElianeMegert** [comment] 2024-05-21 10:04
> > Also having troubles using "old lines" (not robocopy) to copy a folder e.g Copy-File -Path "$dirSupportFiles\Userconfig" -Destination "$envAppData" -Recurse this will endup in error 16. when I toggle off the use of robocopy the command works fine and copies the folder. Is it meant to cover the same syntax? if yes then someone might look into this
> 
> That particular syntax is working fine for me, could you post the output of the log file please and confirm you're using 3.10.1?

Hi, if I run the regular command as in help I already run into troubles:
Copy-File -Path "$dirSupportFiles\*.*" -Destination "$envTemp\tempfiles"

[Freeware_Notepad++_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388195/Freeware_Notepad%2B%2B_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log)

confirming version 3.10.1

**Comment by ElianeMegert** [comment] 2024-05-21 10:04
> > > Also having troubles using "old lines" (not robocopy) to copy a folder e.g Copy-File -Path "$dirSupportFiles\Userconfig" -Destination "$envAppData" -Recurse this will endup in error 16. when I toggle off the use of robocopy the command works fine and copies the folder. Is it meant to cover the same syntax? if yes then someone might look into this
> > 
> > 
> > That particular syntax is working fine for me, could you post the output of the log file please and confirm you're using 3.10.1?
> 
> Hi, if I run the regular command as in help I already run into troubles: Copy-File -Path "$dirSupportFiles*.*" -Destination "$envTemp\tempfiles"
> 
> [Freeware_Notepad++_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388195/Freeware_Notepad%2B%2B_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log)
> 
> confirming version 3.10.1

using system context

**Comment by DanGough** [comment] 2024-05-21 10:06
> The error situation occurs with version 3.10.1. Version 3.10.0 works.

Confirmed, this appears to be a regression with 3.10.1. For now you can use `-UseRobocopy $false` until this is resolved.

**Comment by ElianeMegert** [comment] 2024-05-21 10:31
> > > > > Also having troubles using "old lines" (not robocopy) to copy a folder e.g Copy-File -Path "$dirSupportFiles\Userconfig" -Destination "$envAppData" -Recurse this will endup in error 16. when I toggle off the use of robocopy the command works fine and copies the folder. Is it meant to cover the same syntax? if yes then someone might look into this
> > > > 
> > > > 
> > > > That particular syntax is working fine for me, could you post the output of the log file please and confirm you're using 3.10.1?
> > > 
> > > 
> > > Hi, if I run the regular command as in help I already run into troubles: Copy-File -Path "$dirSupportFiles*.*" -Destination "$envTemp\tempfiles"
> > > [Freeware_Notepad++_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388195/Freeware_Notepad%2B%2B_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log)
> > > confirming version 3.10.1
> > 
> > 
> > using system context
> 
> Your particular issue is caused by this:
> 
> ```
> [Installation] :: Robocopy output:
> ERROR : Invalid Parameter #10 : "/IM"
> ```
> 
> Maybe this was only added to recent versions of Robocopy?! Would you be able to run `robocopy /?` to get the available switches please, and provide your OS version details if /IM is not in the list?
> 
> ```
>                /XJD :: eXclude symbolic links for Directories and Junction points.
>                /XJF :: eXclude symbolic links for Files.
> 
>                 /IM :: Include Modified files (differing change times).
> ::
> :: Retry Options :
> ::
>                /R:n :: number of Retries on failed copies: default 1 million.
>                /W:n :: Wait time between retries: default is 30 seconds.
> ```

attached the infos. /IM is not in the list indeed. that VM uses a quite old vs10 build (1709) used for testing purposes only 
[robocopy_args.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388557/robocopy_args.txt)
[sysinfo.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388558/sysinfo.txt)

**Comment by ElianeMegert** [comment] 2024-05-21 10:32
> > > > > > Also having troubles using "old lines" (not robocopy) to copy a folder e.g Copy-File -Path "$dirSupportFiles\Userconfig" -Destination "$envAppData" -Recurse this will endup in error 16. when I toggle off the use of robocopy the command works fine and copies the folder. Is it meant to cover the same syntax? if yes then someone might look into this
> > > > > 
> > > > > 
> > > > > That particular syntax is working fine for me, could you post the output of the log file please and confirm you're using 3.10.1?
> > > > 
> > > > 
> > > > Hi, if I run the regular command as in help I already run into troubles: Copy-File -Path "$dirSupportFiles*.*" -Destination "$envTemp\tempfiles"
> > > > [Freeware_Notepad++_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388195/Freeware_Notepad%2B%2B_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log)
> > > > confirming version 3.10.1
> > > 
> > > 
> > > using system context
> > 
> > 
> > Your particular issue is caused by this:
> > ```
> > [Installation] :: Robocopy output:
> > ERROR : Invalid Parameter #10 : "/IM"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe this was only added to recent versions of Robocopy?! Would you be able to run `robocopy /?` to get the available switches please, and provide your OS version details if /IM is not in the list?
> > ```
> >                /XJD :: eXclude symbolic links for Directories and Junction points.
> >                /XJF :: eXclude symbolic links for Files.
> > 
> >                 /IM :: Include Modified files (differing change times).
> > ::
> > :: Retry Options :
> > ::
> >                /R:n :: number of Retries on failed copies: default 1 million.
> >                /W:n :: Wait time between retries: default is 30 seconds.
> > ```
> 
> attached the infos. /IM is not in the list indeed. that VM uses a quite old vs10 build (1709) used for testing purposes only [robocopy_args.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388557/robocopy_args.txt) [sysinfo.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388558/sysinfo.txt)

Note: time sync is disabled on that vm thats why the old date\time.

**Comment by ElianeMegert** [comment] 2024-05-21 10:35
> > > > > > > Also having troubles using "old lines" (not robocopy) to copy a folder e.g Copy-File -Path "$dirSupportFiles\Userconfig" -Destination "$envAppData" -Recurse this will endup in error 16. when I toggle off the use of robocopy the command works fine and copies the folder. Is it meant to cover the same syntax? if yes then someone might look into this
> > > > > > 
> > > > > > 
> > > > > > That particular syntax is working fine for me, could you post the output of the log file please and confirm you're using 3.10.1?
> > > > > 
> > > > > 
> > > > > Hi, if I run the regular command as in help I already run into troubles: Copy-File -Path "$dirSupportFiles*.*" -Destination "$envTemp\tempfiles"
> > > > > [Freeware_Notepad++_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388195/Freeware_Notepad%2B%2B_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log)
> > > > > confirming version 3.10.1
> > > > 
> > > > 
> > > > using system context
> > > 
> > > 
> > > Your particular issue is caused by this:
> > > ```
> > > [Installation] :: Robocopy output:
> > > ERROR : Invalid Parameter #10 : "/IM"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Maybe this was only added to recent versions of Robocopy?! Would you be able to run `robocopy /?` to get the available switches please, and provide your OS version details if /IM is not in the list?
> > > ```
> > >                /XJD :: eXclude symbolic links for Directories and Junction points.
> > >                /XJF :: eXclude symbolic links for Files.
> > > 
> > >                 /IM :: Include Modified files (differing change times).
> > > ::
> > > :: Retry Options :
> > > ::
> > >                /R:n :: number of Retries on failed copies: default 1 million.
> > >                /W:n :: Wait time between retries: default is 30 seconds.
> > > ```
> > 
> > 
> > attached the infos. /IM is not in the list indeed. that VM uses a quite old vs10 build (1709) used for testing purposes only [robocopy_args.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388557/robocopy_args.txt) [sysinfo.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388558/sysinfo.txt)
> 
> Note: time sync is disabled on that vm thats why the old date\time.

confirming no issue on win11 22h2

**Comment by ElianeMegert** [comment] 2024-05-21 10:37
> > > > > > > > Also having troubles using "old lines" (not robocopy) to copy a folder e.g Copy-File -Path "$dirSupportFiles\Userconfig" -Destination "$envAppData" -Recurse this will endup in error 16. when I toggle off the use of robocopy the command works fine and copies the folder. Is it meant to cover the same syntax? if yes then someone might look into this
> > > > > > > 
> > > > > > > 
> > > > > > > That particular syntax is working fine for me, could you post the output of the log file please and confirm you're using 3.10.1?
> > > > > > 
> > > > > > 
> > > > > > Hi, if I run the regular command as in help I already run into troubles: Copy-File -Path "$dirSupportFiles*.*" -Destination "$envTemp\tempfiles"
> > > > > > [Freeware_Notepad++_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388195/Freeware_Notepad%2B%2B_8.5.0_x64_EN_001_PSAppDeployToolkit_Install.log)
> > > > > > confirming version 3.10.1
> > > > > 
> > > > > 
> > > > > using system context
> > > > 
> > > > 
> > > > Your particular issue is caused by this:
> > > > ```
> > > > [Installation] :: Robocopy output:
> > > > ERROR : Invalid Parameter #10 : "/IM"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Maybe this was only added to recent versions of Robocopy?! Would you be able to run `robocopy /?` to get the available switches please, and provide your OS version details if /IM is not in the list?
> > > > ```
> > > >                /XJD :: eXclude symbolic links for Directories and Junction points.
> > > >                /XJF :: eXclude symbolic links for Files.
> > > > 
> > > >                 /IM :: Include Modified files (differing change times).
> > > > ::
> > > > :: Retry Options :
> > > > ::
> > > >                /R:n :: number of Retries on failed copies: default 1 million.
> > > >                /W:n :: Wait time between retries: default is 30 seconds.
> > > > ```
> > > 
> > > 
> > > attached the infos. /IM is not in the list indeed. that VM uses a quite old vs10 build (1709) used for testing purposes only [robocopy_args.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388557/robocopy_args.txt) [sysinfo.txt](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/files/15388558/sysinfo.txt)
> > 
> > 
> > Note: time sync is disabled on that vm thats why the old date\time.
> 
> confirming no issue on win11 22h2

No issue on win10 20H2

**Comment by DanGough** [comment] 2024-05-21 13:54
Thanks for this. /IM was added to prevent Robocopy skipping files that already existed on the destination. I will have to do some testing on an older OS version!

**Closed** 2024-07-09 14:03 UTC
Labels: bug, resolved / implemented
