### ISSUE TITLE
Show-InstallationProgress Error "You cannot call a method on a null-valued expression"

### ISSUE THREAD

**Issue by quintos** [PSAppDeployToolkit/PSAppDeployToolkit#1049] opened 2024-09-09 09:55 UTC
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.2

### Describe the bug

Greetings,

I am getting the exception below when calling the function Show-InstallationProgress.
Environment:

Windows 10 22H2
Powershell 5.1.19041.4780

```
[09-09-2024 11:34:51.138] [Pre-Installation] [Deploy Application] :: Error Record:
-------------

Message        : You cannot call a method on a null-valued expression.
InnerException :

FullyQualifiedErrorId : InvokeMethodOnNull
ScriptStackTrace      : at Show-InstallationProgress<Process>, ******\AppDeployToolkit\AppDeployToolkitMain.ps1: line 11492
                        at <ScriptBlock>,
                       *******\Deploy-Application.ps1: line 184
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At **************AppDeployToolkit\AppDeployToolkitMain
                  .ps1:11492 char:13
                  +         If (!(Test-Path -LiteralPath 'variable:ProgressRunspace') -or ...
                  +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Regards,

Quint

### Steps to reproduce

```
 ##*===============================================
      ##* MARK: PRE-INSTALLATION
      ##*===============================================
      [String]$installPhase = 'Pre-Installation'

      Show-InstallationProgress
```

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-US
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:270
+ ... HyperVisorPresent','CsPartOfDomain','CsPCSystemType'); dotnet --infoG ...
+                                                            ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

dotnet : The term 'dotnet' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:552
+ ... 'HyperVisorPresent','CsPartOfDomain','CsPCSystemType'); dotnet --info
+                                                             ~~~~~~
    + CategoryInfo          : ObjectNotFound: (dotnet:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by DanGough** [comment] 2024-09-09 10:08
Unable to reproduce that here - what happens if you run this in a powershell console? 

. .\AppDeployToolkitMain.ps1
Show-InstallationProgress

You should see:

![image](https://github.com/user-attachments/assets/e2513454-d920-4e76-8753-16cc785d2fce)

**Comment by quintos** [comment] 2024-09-09 10:21
I think it was because there was a lock on the banner.png
I remember I opened and close this file prior to executing te installation.
And after the installation error I couldn't delete it. (locked)
After a restart of the computer, the exception does not occur anymore.

**Comment by quintos** [comment] 2024-09-09 10:29
But I noticed that after the installation (successful), And I keep the powershell window running, there is still a lock on the banner file.
So it's not released after the installation proces finishes.
When I close powershell the file is unlocked.

Not really a big problem but nonetheless.

**Comment by mjr4077au** [comment] 2024-09-22 12:16
We're not too far away from our v4 public preview release, where this section of the code is thoroughly reworked and can't ever exhibit this issue. We'd prefer to concentrate effort there, but if more people report being affected by this issue, we'll consider an emergency hotfix for it.

**Comment by LFM8787** [comment] 2024-09-30 19:35
@quintos check out [[Bug] Dispose() method for $appDeployLogoBannerObject not working when async called AppDeployToolkitMain.ps1](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/1059) and its simple solution.

**Comment by mjr4077au** [comment] 2024-09-30 21:06
@LFM8787 this issue is different, but again also taken care of in v4. Going to close this for now.

**Closed by mjr4077au** 2024-09-30 21:06 UTC
Labels: Type: Issue / Bug, Status: Needs Triage, Status: In Progress
