### ISSUE TITLE
How to use Set-PinnedApplication?

### ISSUE THREAD

**Issue by InteXX** [PSAppDeployToolkit/PSAppDeployToolkit#737] opened 2023-01-19 02:27 UTC
**My Question/Issue:**
I don't want to deploy an application; I want to use `Set-PinnedApplication` only to manage command line switches in StartMenu/TaskBar shortcuts to an already-installed application (this is for GPO purposes).

**What I have tried so far:**
Googling the issue. There seems to be absolutely NO guidance—anywhere, including at the official website—on how to get started and actually use this tool. I ran the installation. I got a notification flyout telling me it's been installed. OK, great. What next? There's no Start Menu entry, no nothing. What does this utility do, and how does one get it to do it?

**Screenshots or additional details:**
Again, I don't need to deploy an app. I only need to create a GPO that `runs a script/sets a registry key/bakes a cake` to pin an already-installed application to the StartMenu/TaskBar (with command-line switches—IMPORTANT!).

**----EDIT----**

OK, I was able to run the function by dot-sourcing it:

```
PS D:\Dev\Projects\Git\PSAppDeployToolkit\Toolkit\AppDeployToolkit> . .\AppDeployToolkitMain.ps1
PS D:\Dev\Projects\Git\PSAppDeployToolkit\Toolkit\AppDeployToolkit> Set-PinnedApplication
```

I provided the `Action` and `FilePath` arguments when prompted (using `PinToTaskbar`), and the function ran without errors (after I removed the quotes from the file path).

But I didn't get a pinned TaskBar shortcut (Windows 11). Perhaps this function only works with Windows 10 and earlier?

Also: I _did_ get an error when using `PinToStartMenu`. Here's that result:

> Only shortcut files (.lnk) are supported on Windows 10 and higher

So I've come away from this experience with a plan:

1. I'll use GPO to create/update the `.lnk` shortcut files to the app, to include the command line switches that I need
2. Since pinning preserves the switches from the `.lnk`, I'll swallow the thumbtacks and do the pinning manually (since there doesn't seem to be a way to automate this under Windows 11)

Further suggestions are welcome, thank you.

**Comment by niceguy0815** [comment] 2023-01-19 22:32
eventualy the WIKI Page is helpful?
https://allnewandimproved.psappdeploytoolkit.com/functions/Set-PinnedApplication.html#description

**Comment by InteXX** [comment] 2023-01-20 00:27
@niceguy0815 

Thank you. That documentation is helpful in that it details the correct syntax for the function call. What is decidedly _unhelpful_, however, is the lack of explanation here or at the official website on how to get started from the very beginning. How do we get to the point where we can actually _make_ that function call?

All documentation for this that I've been able to find—anywhere—starts at an intermediate level, falsely assuming that the beginner already knows how to use this tool.

**Comment by That-Annoying-Guy** [comment] 2023-01-20 18:07
Vaguely I remember that to pin any app, the .lnk MUST exist in the Start Menu.

**Comment by InteXX** [comment] 2023-01-20 19:24
@That-Annoying-Guy 

> Vaguely I remember that to pin any app, the .lnk MUST exist in the Start Menu.

Hm, interesting. Yes, that makes sense.

> Also, this issue seems to be a dup of #384

Oops.

FWIW I did find this: https://petri.com/windows-10-pin-apps-taskbar-using-group-policy/

**Comment by mjr4077au** [comment] 2024-10-14 09:09
Duplicate of #384 and #339.

**Closed by mjr4077au** 2024-10-14 09:09 UTC
Labels: Type: Question

**Comment by InteXX** [comment] 2024-10-14 21:05
@mjr4077au 

This is not a duplicate of either of those issues. Please re-review and read carefully.

**Comment by mjr4077au** [comment] 2024-10-14 21:25
> > Also, this issue seems to be a dup of #384
> 
> Oops. Thank you.
It was mentioned here that it's a duplicate of the same issue number that I referenced, which was acknowledged by yourself at the time in 2023. 

Irrespective of this, as mentioned in #339, we've had to drop the function simply because it doesn't work anymore. By your own acknowledgement, it doesn't work on Windows 11 targets you're using, and it only works on the oldest Windows 10 targets at that. 

If a suitable way to manage taskbar pinning is found, we'd love to bring the functionality back, however this broken function can't remain the way it is.

**Comment by InteXX** [comment] 2024-10-14 22:12
@mjr4077au 

> which was acknowledged by yourself at the time

Oops. Thank you.

> we'd love to bring the functionality back

Yes, it's a disappointment. But there're worse things, I suppose.

As @DennisVH mentioned briefly in #384, there appears to be some managed code floating around that can accomplish the goal. You wouldn't happen to be familiar with it or know where it can be found, would you?

**Comment by InteXX** [comment] 2024-10-14 22:21
> unless you're doing it via GPO

Actually, that's _exactly_ the way I wish to do it. Maybe I should alter my search parameters.

**Comment by mjr4077au** [comment] 2024-10-14 22:35
Information on the GPO to use and how to configure it can be found in this link: https://learn.microsoft.com/en-us/windows/configuration/start/layout?tabs=gpo%2Cintune-11&pivots=windows-10#deploy-the-start-layout-configuration

While this is talking about the start menu, the same start menu/taskbar XML is used on Windows 11, except its used only for the taskbar as the start menu has moved to JSON (_not_ configurable via GPO, only a CSP (MDM)).

Pinning of apps relies on shortcuts that already pre-exist, so you can either use the ones in the start menu, or if you need them left alone and to just have specific launch parameters from the taskbar, you can use our `New-Shortcut` to create new shortcuts into a suitable location the user can access, then pin those shortcuts to the taskbar.

Bare in mind that policy-managed pinning like this is enforced. The user can unpin them but they'll re-appear at the next log on. While its frustrating that MSFT have removed the ability to pin apps on an app-by-app basis, it was done for the good of the user, and I do tend to agree as I try to administrate _less_ these days and only configure the minimum.

The other option is to configure your pinning, then inject the files into the device's Default user profile. This won't help existing users, but new log ons will receive your desired pins as a preference, then the user can customise thier pinning thereafter. This is the approach I typically take as I feel the user should have their workstation how I want, not how I think they want it.

**Comment by InteXX** [comment] 2024-10-14 22:39
> I try to administrate less these days and only configure the minimum

Yes, I agree.

> The other option is to configure your pinning, then inject the files into the device's Default user profile

That's a good approach, I like that. I'll add it to my bag of tricks.

Thank you for your assistance today.
