### ISSUE TITLE
60008 error in 3.9.3 from PowerShell Core 7.4.0

### ISSUE THREAD

**Issue by bferg317-perrigo** [PSAppDeployToolkit/PSAppDeployToolkit#849] opened 2023-12-19 16:29 UTC
**Describe the bug**
Running Deploy-Application.ps1 from a PowerShell Core 7.4.0 terminal fails to dot-source AppToolkitMain.ps1, but works under 5.1.x

**To Reproduce**
1. Launch pwsh 7.4.0
2. Call Deploy-Application.ps1

**Screenshots**
![image](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/assets/83671369/9cb5673b-738c-423b-b899-100c0db84265)

**Toolkit Version:**
3.9.3

**Powershell Version:**
7.4.0

**Additional context**
Error: `You cannot call a method on a null-valued expression.`

**Comment by bferg317-perrigo** [comment] 2023-12-19 16:34
Found this testing some of our extensions, but looking at the relevant code block this should be reproducible on a completely stock toolkit.

**Comment by khaffner** [comment] 2024-01-30 12:49
Well, Windows Powershell is the only supported Powershell. Last time I tried loading it with pwsh, it had a bad time with Get-WMIobject I think.

**Comment by seanlillis** [comment] 2024-02-09 09:21
Adding a related issue in VSCode / PS7: https://www.reddit.com/r/PowerShell/comments/17k0p81/psappdeploytoolkit_with_vs_code_error/ @sintaxasn

**Comment by bferg317-perrigo** [comment] 2024-02-09 12:32
> Well, Windows Powershell is the only supported Powershell. Last time I tried loading it with pwsh, it had a bad time with Get-WMIobject I think.

I haven't seen this stated in an official capacity, only this: "However, we recommend using the latest version of PowerShell available for your operating system."

**Comment by mjr4077au** [comment] 2024-03-15 06:02
PowerShell 7.x support, at least initially, should be fixed via #882 and #885.

**Comment by mjr4077au** [comment] 2024-03-15 06:08
This is also a duplicate of #475.

**Comment by sintaxasn** [comment] 2024-06-11 03:18
Closed as duplicate

**Closed** 2024-06-11 03:18 UTC
Labels: bug, duplicate, enhancement
