### ISSUE TITLE
Set-PinnedApplication

### ISSUE THREAD

**Issue by RITSol** [PSAppDeployToolkit/PSAppDeployToolkit#804] opened 2023-05-03 17:42 UTC
I am trying to add an application to the taskbar here. Unfortunately this runs into an error so it looks like this is a bug in the main, right?

We have Windows 10

```powershell
Set-PinnedApplication -Action PintoTaskbar -FilePath "$EnvProgramFiles\Q-Dir\Q-Dir_x64.exe"
``` 

[05-03-2023 19:29:12.248] [Initialization] [Set-PinnedApplication] :: Failed to execute action [PintoTaskbar]. 
Error Record:
-------------In \\cotn.group\IT\GRP\SCCM_Sources\43_PackageFactory\AppDeploymentToolkit\Template\COM_AppDeploy-Template\AppDeployToolkit\AppDeployToolkitMain.ps1:8556 characters:6
              $shellKey = $classesStarKey.CreateSubKey("shell", $true)

Could someone give me a hint if necessary, or is this a bug in the main?
Because $classesStarKey.CreateSubKey does not exist.

Otherwise I have to develop my own function.

Greetings

Markus

**Comment by mjr4077au** [comment] 2024-10-14 11:57
Duplicate of #339.

**Closed by mjr4077au** 2024-10-14 11:57 UTC
