### ISSUE TITLE
[Bug] GetDeploymentStatus of DeploymentSession throws InvalidCastException

### ISSUE THREAD

**Issue by neo42JBR** [PSAppDeployToolkit/PSAppDeployToolkit#1187] opened 2024-12-17 20:41 UTC
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.0.3

### Describe the bug

I open a fresh ADT session and simply call GetDeploymentStatus() which throws an the exception

Error (sorry for the german x):
```
[2024-12-17 21:40:49.928] [Execution] [Invoke-NxtDeployment] [Error] :: Ausnahme beim Aufrufen von "GetDeploymentStatus" mit 0 Argument(en):  "Die angegebene Umwandlung ist ungültig."
Error Record:
-------------

Message               : Ausnahme beim Aufrufen von "GetDeploymentStatus" mit 0 Argument(en):  "Die angegebene Umwandlung ist ungültig."
InnerException        : System.InvalidCastException: Die angegebene Umwandlung ist ungültig.
                           bei PSADT.Module.DeploymentSession.GetDeploymentStatus()
                           bei CallSite.Target(Closure , CallSite , Object )

FullyQualifiedErrorId : InvalidCastException
ScriptStackTrace      : bei Invoke-NxtDeployment<Process>, D:\Repositories\PSAppDeployToolkitExtensionsv4\PSAppDeployToolkit.Neo42Extensions\PSAppDeployToolkit.Neo42Extensions.psm1: Zeile 381
                        bei <ScriptBlock>, D:\Repositories\PSAppDeployToolkitExtensionsv4\Deploy-Application.ps1: Zeile 352

PositionMessage       : In D:\Repositories\PSAppDeployToolkitExtensionsv4\PSAppDeployToolkit.Neo42Extensions\PSAppDeployToolkit.Neo42Extensions.psm1:381 Zeichen:4
                        +             & $CommandTable.'Register-NxtPackageInRegistry'
                        +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error Inner Exception(s):
-------------------------

Message : Die angegebene Umwandlung ist ungültig.
Invoke-NxtDeployment : Ausnahme beim Aufrufen von "GetDeploymentStatus" mit 0 Argument(en):  "Die angegebene Umwandlung ist ungültig."
In D:\Repositories\PSAppDeployToolkitExtensionsv4\Deploy-Application.ps1:352 Zeichen:1
+ Invoke-NxtDeployment -EndScript
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-NxtDeployment], MethodInvocationException
    + FullyQualifiedErrorId : InvalidCastException,Invoke-NxtDeployment
```

### Steps to reproduce

1. $session =  Open-ADTSession -PassThru -SessionState $ExectuionContext.SessionState
2. $session.GetDeploymentStatus()
3. ???

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile

.NET SDK:
 Version:           8.0.404
 Commit:            7b190310f2
 Workload version:  8.0.400-manifests.996cfe54
 MSBuild version:   17.11.9+a69bbaaf5

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.404\

Installierte .NET-Workloads:
Konfiguriert für die Verwendung loose manifests beim Installieren neuer Manifeste.
Es sind keine installierten Workloads zum Anzeigen vorhanden.

Host:
  Version:      8.0.11
  Architecture: x64
  Commit:       9cb3b725e3

.NET SDKs installed:
  8.0.404 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by mjr4077au** [comment] 2024-12-17 21:20
I can't reproduce this. Has there been any changes to the config.psd1 on your side that might affect this?

![image](https://github.com/user-attachments/assets/221c4fa3-2d13-4dc2-a3f6-7723edb5db4d)

```C#
        /// <summary>
        /// Gets the deployment status.
        /// </summary>
        /// <returns>The deployment status.</returns>
        public string GetDeploymentStatus()
        {
            // Extrapolate the UI options from the config hashtable.
            var configUI = (Hashtable)InternalDatabase.GetConfig()["UI"]!;

            if ((ExitCode == (int)configUI["DefaultExitCode"]!) || (ExitCode == (int)configUI["DeferExitCode"]!))
            {
                return "FastRetry";
            }
            else if (AppRebootExitCodes.Contains(ExitCode))
            {
                return "RestartRequired";
            }
            else if (AppSuccessExitCodes.Contains(ExitCode))
            {
                return "Complete";
            }
            else
            {
                return "Error";
            }
        }
```

**Comment by mjr4077au** [comment] 2024-12-18 00:37
I also tested this with a derived PowerShell class (not sure whether you're deriving from our class via C# or PowerShell), and it seems fine too:

![image](https://github.com/user-attachments/assets/5400fbfa-3f66-44a2-b241-7436ba7a8440)

I'll close this one for now, but if you can further isolate what might be causing this, or what specifically about your setup might be causing this, I'm sure we can resolve it together 🤘

**Closed by mjr4077au** 2024-12-18 00:37 UTC
Labels: Type: Issue / Bug, Status: Needs Triage
