### ISSUE TITLE
Remove-MSIApplications Wildcards

### ISSUE THREAD

**Issue by rsaada** [PSAppDeployToolkit/PSAppDeployToolkit#293] opened 2017-08-10 15:58 UTC
I'd like to use Remove-MSIApplications to remove a specific version of an MSI application rather than removing all versions. I know that it's possible to create exclusions but is it possible to use inclusions instead? This options seems to totally ignore version numbers. For example, let's say I want to remove Google Earth version 7x but no higher or lower version. None of these commands work:
Remove-MSIApplications -Name 'Google Earth 7'
Remove-MSIApplications -WildCard 'Google Earth 7'
Remove-MSIApplications -WildCard '*Google Earth 7*'

Is it not possible to include the version number in the search? Does it only accept the product name?
Thanks

**Comment by rilax1010** [comment] 2017-08-11 09:10
It's already possible by using parameters `-Exact, -WildCard, -FilterApplication or -ExcludeFromUninstall`

**Comment by rsaada** [comment] 2017-08-11 16:50
Can you please provide an example on how to remove a specific version of an application, including a minor version?

**Comment by rsaada** [comment] 2017-08-17 14:45
Thanks for your reply but that command doesn't seem to work. Here are the registry parameters for the package I'm trying to remove:
DiplayName: 7-Zip 16.02 (x64 edition)
DiplayVersion: 16.02.00.0

Commands I tried in Deploy-Application.PS1:
Remove-MSIApplications -Name '7-Zip 16.02 (x64 edition)' -FilterApplication @(@('DisplayVersion',16*','WildCard'))

Remove-MSIApplications -Name '7-Zip 16.02 (x64 edition)' -FilterApplication @(@('DisplayVersion',16.02*','WildCard'))

Remove-MSIApplications -Name '7-Zip 16.02 (x64 edition)' -FilterApplication @(@('DisplayVersion',16.02.00.0','Exact'))

All these command failed. Here is what the log said:
[Pre-Installation] :: Found installed application [7-Zip 16.02 (x64 edition)] version [16.02.00.0] using regex matching for search term [7-Zip 16.02 (x64 edition)].                           1/1/1601 12:00:00 AM    0 (0x0000)
[Pre-Installation] :: Found [1] application(s) that matched the specified criteria [7-Zip 16.02 (x64 edition)].                            1/1/1601 12:00:00 AM    0 (0x0000)
[Pre-Installation] :: Filter the results to only those that should be uninstalled as specified in parameter [-FilterApplication].                            1/1/1601 12:00:00 AM    0 (0x0000)
[Pre-Installation] :: No applications found for removal. Continue...                           1/1/1601 12:00:00 AM    0 (0x0000)

**Comment by HpotsirhcH** [comment] 2017-08-18 09:57
I tested that. I find out that this is a bug in the Toolkit. 
It behaves as follows:
 - In case you define a -FilterApplication Parameter with 2 Filters it works as intended
- In case you define a -FilterApplication Parameter with 1 Filter it works not as intended, because in line 2519 (ForEach ($Filter in $FilterApplication) ) it split the one Filter in there Components 
In the Example: -FilterApplication @(@('DisplayVersion',16*','WildCard')) 
 - in Displayversion as one $Filter, 
 - 16* in one $Filter 
 - Wildcard in one $Filter. 
So he cant Check if this Filter Match and dont apply this filter. This need to be fixed in the toolkit main.

@rsaada you can help yourself with a empty additional Filter like this:
Remove-MSIApplications -Name '7-Zip 16.02 (x64 edition)' -FilterApplication @(@('DisplayVersion','16*','WildCard'),@())

**Comment by rsaada** [comment] 2017-08-18 14:23
Thanks for your help! The command you suggested worked. Hopefully the Toolkit code can be fixed soon.

**Comment by PLogFinder** [comment] 2017-09-14 02:40
It's because the doco is incorrect on how to pass a collection (list) of collections (lists) in Powershell - you don't use nested @(@( a,b,c )).  You need to use the list operator (,comma) like so:    (,(a,b,c)) in your parameters for one Filter or Exclusion, and for two Filters/Exclusions you would need: ((a,b,c),(x,y,z)).   If you want to know more about @(), it guarantees a list, but does *not* make an embedded list when it's already a list.  Filters and Exclusions for the Remove-MSIApplications cmdlet require a list of lists, so use comma and parentheses as I've s hown here.

**Comment by seanlillis** [comment] 2017-10-06 20:32
Thanks for pointing this out. The examples had already been updated in the main script, I've now updated the documentation accordingly for the next release.

**Comment by seanlillis** [comment] 2018-02-13 23:56
This is fixed in v3.7.0.

**Closed by seanlillis** 2018-02-13 23:56 UTC
Labels: resolved
