### ISSUE TITLE
[Bug] Configure-EdgeExtension  errors on line 16517 char:40 - Add-Member : Cannot bind argument to parameter 'InputObject' because it is null.

### ISSUE THREAD

**Issue by DavidHislop** [PSAppDeployToolkit/PSAppDeployToolkit#984] opened 2024-05-01 16:21 UTC
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.0

### Describe the bug

Trying to add a edge extension with the new function. Below is line I am trying.

Configure-EdgeExtension -configureMode Add -extensionID "banejkelfpdmmmfobepfdnbmbbnecnol" -InstallationMode force_installed 
Add-Member : Cannot bind argument to parameter 'InputObject' because it is null.
ppDeployToolkitMain.ps1:16517 char:40
+ ... xtensions | Add-Member -Name $($extensionID) -Value $(@{ "installatio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Member], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberComm 
   and
   
  It seems to create the regSz Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge  ExtensionSettings
  but it just remains null. I am guessing this is due to the value being null in the first place.

### Steps to reproduce

1.Load module
2.Run command line
3. Receive Error

### Environment data

```console
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
KeyboardLayout       : en-GB
TimeZone             : (UTC+00:00) Dublin, Edinburgh, Lisbon, London
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile
```

**Comment by seanlillis** [comment] 2024-05-01 21:01
Duplicate of #931 which was resolved in an earlier commit.

**Closed** 2024-05-01 22:50 UTC
Labels: bug, resolved / implemented
