### ISSUE TITLE
[Accessibility] PsAppDeployToolkit pop-up content not read by screen readers software (Windows Narrator / NVDA / Jaws …)

### ISSUE THREAD

**Issue by msftedad** [PSAppDeployToolkit/PSAppDeployToolkit#702] opened 2022-03-02 23:34 UTC
**Describe the bug**
We are using a customized version of PSAppDeployToolkit to create software packages for SCCM. This powershell templating tool can display different popups to the user. We detected two different behaviors of screen readers :
 When executing PSADT package as user the text popup is correctly processed by the screen readers software
 When executing PSADT package as NT\LOCALSYTEM (default behavior when we deploy the packages inside SCCM), no text is read.

**To Reproduce**
The Full way : (see below for the short version)
- Download PsAppDeployToolkit 3.8.4 (https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/releases)
- Extract the “Toolkit” Folder and use cmdlet Unblock-File *.* in the “Toolkit” and in the “\AppDeployToolkit“ folders to allow further scripts execution
- Open “Deploy-Application.ps1” with a text editor
- Line 120, replace the whole line by:
Show-InstallationWelcome -CloseApps 'iexplore,msedge' -AllowDefer -DeferTimes 99 -CheckDiskSpace -PersistPrompt
- Start Microsoft Edge
- Start the Windows Narrator
- Right click on deploy-application.exe and “Execute as Administrator”
- After a moment, a pop-up is displayed in the OS language:
<image 1>

- The inner text and title are read partially => This is the expected behavior
- Click on “Close Program” and the pop-up will close and Microsoft Edge will close.
- Open the Edge.
- Download the Sysinternal https://download.sysinternals.com/files/SysinternalsSuite.zip
- Unzip the downloaded file.
- Copy the PSEXEC.EXE tool from the Sysinternal folder  and paste it in the same folder as Deploy-application.exe exist
- Open a command prompt as administrator :
- Run command :
"Full\Path\To\Tookit\ psexec.exe present in the Toolkit folder” -i -s "Full\Path\To\Tookit\Deploy-Application.exe"
- This will execute the same file but as NT\LocalSystem with interactive session
- After a while, the same pop-up appears :
<image 2>

- This time no text is correctly read by the Windows Narrator => We are in this context in our SCCM deployments and we want to have a proper reading of the popup in this context.

The Short way :
- Create a powershell test file called… test.ps1
- Add :
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")

$form = New-Object Windows.Forms.Form
$form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::FixedDialog
$form.MaximizeBox = $False
$form.MinimizeBox = $False

$form.Text = "Hello world..."
$form.Size = New-Object System.Drawing.Size(400,370)

$label_prez = New-Object System.Windows.Forms.Label
$label_prez.Location = New-Object System.Drawing.Point(20,20)
$label_prez.Size = New-Object System.Drawing.Size(100,20)
$label_prez.Text = "I am a label"

$button_quit = New-Object System.Windows.Forms.Button
$button_quit.Text = "Close"
$button_quit.Size = New-Object System.Drawing.Size(355,40)
$button_quit.Location = New-Object System.Drawing.Size(20,280)
$button_quit.Add_Click(
{
$form.Close();
})
![image 2](https://user-images.githubusercontent.com/93735775/156467553-5a67c72c-f889-4c90-ac99-3a9b1322a0ac.png)
![image 1](https://user-images.githubusercontent.com/93735775/156467557-4cb5868f-09de-489a-bc7d-29614f7a71fb.png)

$form.AccessibleRole = [Windows.Forms.AccessibleRole]::Dialog
$label_prez.AccessibleRole = [Windows.Forms.AccessibleRole]::StaticText
$form.Controls.Add($label_prez)
$form.Controls.Add($button_quit)
$form.ShowDialog()
- Save
- Execute with: powershell.exe -file test.ps1
- The pop-up is correctly read by Windows Narrator
- Start it as localsystem with : psexec.exe -i -s powershell.exe “Full\Path\to\test.ps1”
- The pop-up is not read by Windows Narrator

Expected Results:
When executed as localsystem, the pop-up should be correctly read by screen readers

Current Results:
Pop-up content is not read. (the demo involves the Windows Narrator, but we get the same result with NVDA)

**Screenshots**

**Toolkit Version:**
PSAppDeployToolkit 3.8.4

**Powershell Version:**
Version of Powershell you are using to run the toolkit. For example: 5.1

**Additional context**
We provided two ways of testing the behavior of a Powershell WinForms Window, the first involves PSADT and is closer of what we get, the second is just a plain Winforms window without PSADT (so you can see that the behavior is not related to a PSADT bug)

**Comment by Sulquendi** [comment] 2022-03-17 10:48
Hello !

The Powershell code given in the last part of your bug submission (called "The Short Way") only involve a standard WinForms pop-up and no specific PSADT function. 

This leads me to say that this is not a issue specifically related to PSADT. What i unsterstand is : 

- The pop-up uses a standard Winforms technology
- The pop-up content is correctly processed by screen readers when launched in a user/admin context
- The content is NOT processed (or badly processed) when launched in a system context
=> Then the issue is most certainly linked to the execution context.

If i am right, then a popup using another technology (i.e. a XAML pop-up using WPF techno) would also be incorrectly processed by screen readers when started in system context (and would be OK in user/admin context)

Regards

**Comment by Sulquendi** [comment] 2022-03-17 13:33
Hi again, msftedad team :)

i downloaded the PsExec tool from Sysinternals to perform further testing. I give you the very simple steps to reproduce the different behaviors (and yes, it is not PSADT related) : 

- Open a dos prompt as admin
- start Windows Narrator 
- Focus your dos prompt and notice that Windows Narrator is able to read it
- type "psexec -i -s cmd" it will open another dos prompt, this time in LocalSystem context
- Focus it ... Notice that Windows Narrator is not able to read it

You can close the narrator. Now run the narrator with system rights using psexec -i -s %windir%\system32\narrator.exe
Try focus your cmd in localsystem context => Yay! it will be read by Windows Narrator.

Rinse and repeat with NVDA (running it as usual or with localsystem context) => same result.

Conclusion : a screen reader cannot access a window in LocalSystem context unless it is ran in the same context.

**Comment by seanlillis** [comment] 2023-01-06 17:07
Closing as this is a Windows execution context issue that cannot be fixed by the PSADT team, as kindly explained by @Sulquendi above and as confirmed by Microsoft in this thread: https://github.com/dotnet/winforms/issues/7658

**Closed by seanlillis** 2023-01-06 17:07 UTC
