### ISSUE TITLE
Close apps countdown timer does not work in Show-InstallationWelcome

### ISSUE THREAD

**Issue by mmashwani** [PSAppDeployToolkit/PSAppDeployToolkit#7] opened 2015-04-14 06:31 UTC
The close apps countdown timer does not update on screen or automatically close applications and continue with install once the timer allowed for the timer has expired.

**Comment by seanlillis** [comment] 2018-01-09 21:46
Can't reproduce the issue, may have been resolved since this issue was raised. Closing.

**Closed by seanlillis** 2018-01-09 21:46 UTC
Labels: bug, resolved
