### ISSUE TITLE
Restart Prompt doesn't fire (+ my fixes)

### ISSUE THREAD

**Issue by ItsThatDood** [PSAppDeployToolkit/PSAppDeployToolkit#713] opened 2022-05-06 00:19 UTC
**Describe the bug**
Show-InstallationRestartPrompt doesn't appear when called.

**To Reproduce**
Create a deployment script
call Show-InstallationRestartPrompt -CountdownSeconds 60 -CountdownNoHideSeconds 30

**Screenshots**

**Toolkit Version:**
3.8.4

**Powershell Version:**
5.1

**Additional context**
AppDeployToolkitMain.ps1
Remove the Hidden WindowStyle and ErrorAction for the restart powershell process on line 7908 and set the Powershell process to -NoExit (so we can see what error it is throwing)
The powershell script that runs returns that there is no parameter called 'Title'
Line 12039 - add $appDeployMainScriptAsyncParameters.Remove('Title') fixes this error

Additionally, when calling with parameters the following occurs:
Show-InstallationRestartPrompt - Line 7891
The switch block is returning a string with " -  - " missing the key and value parameters for the restart prompt
Pulling $_.Key and $_.Value to its own variables at the top and using those in the switch block instead fixes the issue

Am i doing something wrong, or is this actually a bug? I see there have been people on Reddit with similar issues.
It seems like Show-InstallationRestartPrompt is being sent a Title attribute via the $appDeployMainScriptAsyncParameters hash table

**Comment by seanlillis** [comment] 2022-12-28 22:27
Hi @ItsThatDood, I can't reproduce this issue. 

Can you provide a copy of your Deploy-Application.ps1 script please and the log files / error messages you have captured? 

Are you populating the AppVendor/AppName/AppVersion variables in your Deploy-Application.ps1 script?

**Comment by That-Annoying-Guy** [comment] 2022-12-29 16:42
I believe it's fixed in 3.8.5. beta.

https://discourse.psappdeploytoolkit.com/t/show-installationrestartprompt-not-working-in-3-8-4/3319/4

**Closed** 2023-01-12 21:33 UTC
Labels: bug, resolved / implemented
