### ISSUE TITLE
 [PSADT.UiAutomation] does not contain a method named 'SetProcessDPIAware'

### ISSUE THREAD

**Issue by That-IT-GUY-1805** [PSAppDeployToolkit/PSAppDeployToolkit#959] opened 2024-04-17 19:13 UTC
**Describe the bug**
When running Deploy-Application.ps1 in Powershell on Windows 10 I get this exception. This happens on the base template with zero customizations.

I added the @@@ in place of my username and Company

PS C:\Users\@@@@\OneDrive - @@@@INC\Intune\IntunePackagescomplete\2-PendingEvaluation\AutoDesk-Fusion360> .\Deploy-Application.ps1
C:\Users\@@@@\OneDrive - @@@@@INC\Intune\IntunePackagescomplete\2-PendingEvaluation\AutoDesk-Fusion360\Deploy-Application.ps1 : Module [C:\Users\@@@@\OneDrive - @@@@@
INC\Intune\IntunePackagescomplete\2-PendingEvaluation\AutoDesk-Fusion360\AppDeployToolkit\AppDeployToolkitMain.ps1] failed to load:
Method invocation failed because [PSADT.UiAutomation] does not contain a method named 'SetProcessDPIAware'.

At C:\Users\@@@@\OneDrive - @@@@@INC\Intune\IntunePackagescomplete\2-PendingEvaluation\AutoDesk-Fusion360\Deploy-Application.ps1:154 char:13
+             . $moduleAppDeployToolkitMain
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At line:1 char:1
+ .\Deploy-Application.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Deploy-Application.ps1

If i run the deploy.exe works fine but if i run the ps1 to track issues i get the error, i can get it to work if i comment out the below in AppDeployToolkitMain.ps1]
## [System.Void][PSADT.UiAutomation]::SetProcessDPIAware()

**Toolkit Version:**
Version of our toolkit you are using. For example: 3.10.0

**Powershell Version:**
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional context**

**Comment by That-IT-GUY-1805** [comment] 2024-04-17 19:14
i have made sure i am using the latest 3.10.0 files everything was moved to a new folder once downloaded then deploy.ps1 edited

**Comment by rinseaid** [comment] 2024-04-19 23:18
Same issue here. Running inside a Hyper-V virtual machine, if that makes any difference. None of the displays involved are high resolution - dual monitors with 1920x1080p resolution.

**Comment by DanGough** [comment] 2024-04-20 09:06
Please could you both confirm if you were using:

- Old style Powershell console
- Powershell ISE
- Windows Terminal
- VSCode
- Something else?

Also, does it work via Deploy-Application.exe?

**Comment by DanGough** [comment] 2024-04-20 09:11
Also, if you have the unofficial PSADT PowerShell module installed, can you try uninstalling it in case it’s causing a conflict?

**Comment by DanGough** [comment] 2024-04-21 01:41
I have replicated in testing by doing either of the following:

- Run AppDeployToolkitMain.ps1 from 3.9.3 or earlier, trying to run 3.10.0 in the same session
- Install unofficial PSADT module 3.9.3 or earlier, then either run Import-Module PSADT, or attempt to run one of the PSADT commands before running 3.10.0

These are not really supported scenarios, so I doubt anything will be implemented to resolve this. The solution is simply to always ensure you are running in a clean Powershell environment; deploying your application via Deploy-Application.exe should accomplish this. I'll close this for now, but it it's affecting actual deployments, please comment with further info and we can re-open and investigate.

One possible solution is to change the namespace whenever we introduce a breaking change or new class in AppDeployToolkitMain.cs, e.g:

```C#
namespace PSADT_v3.10.0
```
```powershell
[System.Void][PSADT_v3.10.0.UiAutomation]::SetProcessDPIAware()
```

But that isn't a common convention, involves more maintenance, and looks ugly.

**Closed by DanGough** 2024-04-21 01:41 UTC
Labels: bug

**Comment by rinseaid** [comment] 2024-05-20 22:17
@DanGough, late in replying, but you're absolutely right - I had an old version of the module installed. Uninstalling it cleared up the issue. Thanks.

**Comment by DanGough** [comment] 2024-06-20 12:42
@ClientSupportCDB please can you check if you have the PSADT PowerShell module installed?

**Comment by That-IT-GUY-1805** [comment] 2024-06-20 14:15
these are the only ones i have installed

 Get-InstalledModule

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.19.0     Microsoft.Graph.Authentication      PSGallery            Microsoft Graph PowerShell Authentication Module.
2.19.0     Microsoft.Graph.Devices.Corporat... PSGallery            Microsoft Graph PowerShell Cmdlets
2.7.0      Microsoft.Graph.Groups              PSGallery            Microsoft Graph PowerShell Cmdlets
6.1907.1.0 Microsoft.Graph.Intune              PSGallery            PowerShell SDK for Microsoft Intune Graph API
0.9.0.6    PendingReboot                       PSGallery            Module to detect Windows OS pending reboots.
5.6        WindowsAutoPilotIntune              PSGallery            Sample module to manage AutoPilot devices using ...


is there anything you would like me to try?

**Comment by baunai** [comment] 2024-06-20 14:20
I've run into same issue with latest 3.10.1 standalone package on Windows 10 22H2 and no PSADT module installed. I have to comment out this line System.Void][PSADT.UiAutomation]::SetProcessDPIAware() in AppDeployToolkitMain for it to run.

**Comment by DanGough** [comment] 2024-06-20 17:41
Make sure you've updated all the files in the toolkit folder, particularly the .cs file in addition to Main. Also, if you execute a 3.9 or older deployment script then try to run a 3.10.1 one from the same Powershell session, I would expect this error.

**Comment by ClientSupportCDB** [comment] 2024-06-24 05:15
> Make sure you've updated all the files in the toolkit folder, particularly the .cs file in addition to Main. 

Sure, that files were directly executed from the downloaded zip file contributed from here. 

Get-InstalledModule does not return anything because we do not install any modules

> Also, if you execute a 3.9 or older deployment script then try to run a 3.10.1 one from the same Powershell session, I would expect this error.
Not the same session. Never been on that client and never runned a PSAppDeployToolkit Script with this user before on this client.

so, no: its not a users fault!

**Comment by Knuppel1983** [comment] 2025-03-03 08:46
For me the problem is dot-sourcing not being allowed. Win11 has tightened security on constrained language mode.
Strangely, starting via exe file does work.

**Comment by mjr4077au** [comment] 2025-03-03 09:56
@Knuppel1983 please don't necro old, closed issues. 3.x is dead, this simply isn't an issue anymore.
