### ISSUE TITLE
BlockExecution still active in the post-installation

### ISSUE THREAD

**Issue by jopels** [PSAppDeployToolkit/PSAppDeployToolkit#300] opened 2017-09-14 13:13 UTC
Hi,
I blocked the execution of Lync (the program I want to update) via 
`Show-InstallationWelcome -CloseApps 'lync' -BlockExecution`
In the post-installation I want to start Lync via 
`Execute-ProcessAsUser -RunLevel LeastPrivilege -Path 'C:\Program Files (x86)\Microsoft Office\Office16\lync.exe'`
Sometimes I get the error message that the program cannot be started until the Installation is terminated, sometimes just nothing happens.
I found out that I can get around this problem by removing one registry key:
`Remove-RegistryKey -Key 'HKEY_Local_Machine\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lync.exe' -Name 'Debugger'`
Now the question is: Is this a bug or a feature that the program is still locked in the post-installation?
If this is meant to be this way, is there a nicer way to solve this problem then just by removing the registry key manually?

**Comment by jopels** [comment] 2017-09-15 15:04
I switched to calling the function 
`Unblock-AppExecution` 
Even though it is advised against to do so.
This Function is normally called by the script when 
`Exit-Script -ExitCode $mainExitCode`
is called.
Will there be a cleaner way of doing this in future releases?

**Comment by That-Annoying-Guy** [comment] 2017-09-26 21:13
I've had this happen to me. 
In my case I suspect it happens when the package fails and the script exits without calling Unblock-AppExecution.

If I play with blocking execution again, I'll try to cause this issue.

**Comment by seanlillis** [comment] 2017-10-04 21:51
Can you share the log file from an installation that left the application blocked?

**Comment by jopels** [comment] 2017-10-05 15:02
[Here](https://gist.github.com/jopels/0e9e20c22528b64d71aafdd1162ef51c) you go. The script should open lync.exe after the deployment, but lync is not started, as it is still blocked. (I deactivated my solution above.)
The used code:
`#Unblock-AppExecution`
`#Start-Sleep -Seconds 15`
`Execute-ProcessAsUser -RunLevel LeastPrivilege -Path 'C:\Program Files (x86)\Microsoft Office\Office16\lync.exe'`

**Comment by That-Annoying-Guy** [comment] 2017-10-05 15:32
Sorry Sean, that was almost a year ago. I'm assuming I did it to myself during the development of the the package with a debugger and stopped Exit-Script from running and cleaning up.

I'm not even sure how I fixed it. I must have used Unblock-AppExecution or Show-InstallationWelcome or just re-ran the package.

I would just close this and deal with the issue when/if it comes back.

**Comment by seanlillis** [comment] 2017-10-06 22:20
@That-Annoying-Guy Hey, thanks! It's good to be back :-)

@jopels This is expected behavior. As you know, Unblock-AppExecution is only called by Exit-Script, which is only invoked after post-installation. This was set as the default behavior, because there may be post-installation scenarios that also require app execution to be blocked, so rather than requiring the apps to be blocked again, they remain blocked until Exit-Script is called. I still think this behaviour makes more sense than unblocking app execution as standard before the post installation section.

Calling the Unblock-AppExecution function from Deploy-Application.ps1 script before the post-installation section is the best way to achieve what you need to.

**Comment by PLogFinder** [comment] 2017-10-11 06:12
To consider:  f you need another impacted application blocked from beginning to end (eg dependent app getting plugins, like word, outlook) - then put them in the block list in Show-InstallationWelcome.  If you simply need to stop some programs or services belonging to the application you are updating, then just do Stop-Process.  I've found that in practice they are not started again by the user while the application is updating them.

**Comment by jopels** [comment] 2017-10-11 11:26
@PLogFinder I took that into consideration but if you use Stop-Process the user will not be informed that the program will be closed.
I have a solution which works for me. I just think there should be an official and documented way to unblock applications. ;-)

**Comment by seanlillis** [comment] 2017-11-12 20:34
The Unblock-AppExecution function is documented as an internal toolkit function, because it's primary purpose is to be called from Show-InstallationWelcome -BlockExecution, but there is no issue running it yourself.

**Closed by seanlillis** 2017-11-12 20:34 UTC
Labels: wontfix
