### ISSUE TITLE
crash on finnish language

### ISSUE THREAD

**Issue by annegerben** [PSAppDeployToolkit/PSAppDeployToolkit#364] opened 2018-06-29 07:01 UTC
the toolkit crashes on finnish language:

`[Pre-Installation] :: The specified date/time [25. kesäkuutata 2018 8:02:55] is not in a format recognized by the current culture [fi-FI]. 
Error Record:
-------------

Message        : Exception calling "Parse" with "2" argument(s): "The string wa
                 s not recognized as a valid DateTime. There is an unknown word
                  starting at index 4."
InnerException : System.FormatException: The string was not recognized as a val
                 id DateTime. There is an unknown word starting at index 4.
                    at System.DateTimeParse.Parse(String s, DateTimeFormatInfo 
                 dtfi, DateTimeStyles styles)
                    at CallSite.Target(Closure , CallSite , Type , Object , Obj
                 ect )

FullyQualifiedErrorId : FormatException
ScriptStackTrace      : at Get-UniversalDate<Process>, C:\_SMSTaskSequence\Pack
                        ages\PS100974\AppDeployToolkit\AppDeployToolkitMain.ps1
                        : line 5475
                        at Show-InstallationWelcome<Process>, C:\_SMSTaskSequen
                        ce\Packages\PS100974\AppDeployToolkit\AppDeployToolkitM
                        ain.ps1: line 5833
                        at <ScriptBlock>, C:\_SMSTaskSequence\Packages\PS100974
                        \Deploy-Application.ps1: line 151
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\_SMSTaskSequence\Packages\PS100974\AppDeployToolkit\App
                  DeployToolkitMain.ps1:5475 char:4
                  +             [datetime]$DateTime = [datetime]::Parse($DateTi
                  me, $cultu ...
                  +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ~~~~~~~~~~



Error Inner Exception(s):
-------------------------

Message        : The string was not recognized as a valid DateTime. There is an
                  unknown word starting at index 4.
InnerException : 
`

**Comment by That-Annoying-Guy** [comment] 2018-06-29 21:12
to get help we'll need more info like the **Version of the toolkit** you used.

**Comment by annegerben** [comment] 2018-06-29 21:30
fair enough :-) 
we're using latest version, 3.7.1 and windows 10 RS2 (1703)

**Comment by DennisVH** [comment] 2018-08-12 19:47
I installed the Finnish language pack but was not able to recreate the issue.
@annegerben, can you please provide the complete Show-InstallationWelcome commandline you used that caused this inner exception.

**Comment by annegerben** [comment] 2018-08-13 07:25
@DennisVH 
I have also a hardtime to reproduce the issue, be we see it in production.
Looks like also locale and other regional settings must be set to finnish/finland.

`
## Show Welcome Message, allow up to 3 deferrals over max 5 days since first run, and persist the prompt,
        ## When dialog is shown, timeout after 90 minutes and select continue.
        If ($usersLoggedOn) {
  		    Show-InstallationWelcome -AllowDefer -DeferTimes 3 -ForceCountdown 5400 -DeferDays 5 -PersistPrompt -CustomText -SetCustomText $ForceCustomText

		    $bat = Test-Battery -PassThru
		    If ($bat.IsLaptop -eq $true) {
                $loop = 1
                While ($bat.IsUsingACPower -eq $false) {
				    Write-Log -Message Loop ${loop} Laptop running on battery -Source PSAD -LogType CMTrace
                    if ($loop -gt 2) {
                        Write-Log -Message Loop ${loop} Laptop still running on battery, installation cancelled -Source PSAD -LogType CMTrace
				        Exit-Script -ExitCode 60012
                    }
                    [string]$PowerMessage = -join (Your laptop is not connected to mains power.`n`n,
                                                   Please connect to mains power and click OK to proceed.)
                    Show-InstallationPrompt -PersistPrompt -Icon Warning -Message $PowerMessage -ButtonRightText 'OK'
                    # Wait a couple of seconds for AC power to register
                    Start-Sleep -Seconds 2
          		    $bat = Test-Battery -PassThru
                    $loop++
			    }
		    }
        } else {
            # No user logged in
            If ($bat.IsLaptop -eq $true -and $bat.IsUsingACPower -eq $False) {
                Write-Log -Message No user logged in, but laptop is running on battery -Source PSAD -LogType CMTrace
                Exit-Script -ExitCode 60012
            }
        }
        # End
`

**Comment by DennisVH** [comment] 2018-09-06 09:51
@annegerben 
Did you modify the Show-InstallationWelcome function? It does not have a SetCustomText parameter.

**Comment by sintaxasn** [comment] 2018-11-06 20:13
This issue was moved to https://discourse.psappdeploytoolkit.com/t/crash-on-finnish-language/1144

**Comment by oohlaf** [comment] 2019-01-04 12:16
This issue was caused by FullDateTimePattern returning a localized culture dependent string which is not always parsed back correctly. Changing this to universaldatetimepattern fixes it.

**Comment by oohlaf** [comment] 2019-02-13 18:53
Any news on merging the fix?

**Comment by annegerben** [comment] 2019-02-15 08:00
thanks!

**Comment by DennisVH** [comment] 2019-02-28 09:48
This will be fixed in the next release

**Closed** 2020-05-21 06:14 UTC
Labels: resolved/implemented
