### ISSUE TITLE
Get-RunningProcesses bug with UWP apps (suspended state)

### ISSUE THREAD

**Issue by CBennerstedt** [PSAppDeployToolkit/PSAppDeployToolkit#573] opened 2020-10-19 10:27 UTC
**Describe the bug**
Due to the nature of UWP apps, they can go into suspended mode for the processes when a user exits the app.
In my example, I am utilizing Show-InstallationWelcome for MicrosoftEdge process (legacy Microsoft Edge browser) and is about to upgrade to new Edge Chromium.
The old edge (MicrosoftEdge.exe) process goes to suspended state for user by default when Show-InstallationWelcome urges user to close the app, this results in Show-InstallationWelcome not continuing on it's own and is confusing for a user which would then be required to click End program to kill the process.

My workaround is to extend the Get-RunningProcesses function and add a check for Responding property of the process:
The line :
`[Diagnostics.Process[]]$runningProcesses = Get-Process | Where-Object -FilterScript $whereObjectFilter | Sort-Object ProcessName`

Is changed to:

`[Diagnostics.Process[]]$runningProcesses = Get-Process | Where-Object -FilterScript $whereObjectFilter | Where-Object -Property Responding -EQ $true | Sort-Object ProcessName`

Now, the Show-InstallationWelcome dialog will continue as soon as the process enter Responding state of $false (which it does approx. after 30 seconds), which is not perfect but better.

**To Reproduce**
1. Make sure UWP Microsoft Edge is running (MicrosoftEdge.exe)
2. Run PADT with Show-InstallationWelcome for UWP Microsoft Edge (MicrosoftEdge.exe) process
3. You will enter an endless loop where PADT thinks MicrosoftEdge.exe is running even though user exited the app, but the app is in suspended state

**Toolkit Version:**
3.8.3

**Powershell Version:**
5.1

**Comment by luki1412** [comment] 2020-10-30 07:27
I just tried with suspended Skype and it worked just fine. This could be related to our CloseApps issue instead, where we used PID to close the process not the name. Could you download the Main script from our repository and test this again?

**Comment by cribban** [comment] 2020-11-13 15:32
Sorry for slow answer. I tried using current AppDeployToolkitMain.ps1 from repository and it's not working correctly.
What is working is the "Close Programs" button, and it was working previously as well.

The issue is the automatic closing of the dialog that is not working when the app is closed by the user and the app is going to suspended state, which when I tweaked the Get-RunningProcesses the dialog does auto-close but after around 30 seconds when the app moves from state running to state suspended.

**Comment by luki1412** [comment] 2020-11-13 16:56
If you are using -ForceCloseAppsCountdown and not -ForceCountdown then it should work. The logic in the current script file was changed to close it by name. -ForceCountdown clicks Continue which doesnt close apps and just reopens the window causing a loop.

**Closed** 2021-01-13 10:39 UTC
Labels: bug, resolved/implemented
